### ISSUE TITLE
Número endereço

### ISSUE THREAD

**Issue by cyrocostsolution** [pagseguro/prestashop#100]
Boa tarde,

Uma dúvida que não encontrei resposta ainda, com relação ao número do endereço, existe alguma forma de parametrizar para o cliente digitar previamente e não ficar pendente no momento de selecionar a forma de pagamento ?

Grato

![Screenshot_466](https://user-images.githubusercontent.com/51411678/83947537-fc49bc80-a7ed-11ea-86f0-ed4d119505d3.png)

**Comment by prestabr** [comment]
Boa Tarde cyrocostsolution,

As informações pessoais e endereço do cliente devem ser tratadas na tela de cadastro da loja, antes de chegar no checkout.

O ideal é que você utilize um módulo para adaptar/customizar a sua loja para o padrão de cadastro brasileiro. O módulo de checkout transparente é compatível com diversos disponíveis na web (pagos e gratuitos).

Se você não quiser utilizar um módulo para padronizar o cadastro e precisa apenas capturar o numeral do endereço, pode utilizar o campo "company" da tabela "ps_address", disponibilizado na tela de cadastro de endereço - o módulo de checkou entende este padrão.

Estas informações são fundamentais para processar o pagamento: cpf, endereço, numeral do endereço, bairro, cidade, estado, telefone ou celular.

Atenciosamente,
Equipe PrestaBR

**Comment by cyrocostsolution** [comment]
Boa tarde,
ok, funcionou, Muito obrigado.
em breve irei comprar um módulo.
Grato
