### ISSUE TITLE
Desconto para pagamento em boleto não está sendo aplicado

### ISSUE THREAD

**Issue by sarinalustosa** [pagseguro/prestashop#101]
Olá,
Tenho o módulo do pagseguro para a versão da prestashop 1.6.1.24 e mesmo configurando no módulo do pagseguro para dar 10% de desconto para boleto, ao gerar o boleto este desconto não é aplicado.

![image](https://user-images.githubusercontent.com/31964035/84033445-3c847880-a96f-11ea-8a95-91707ca7e624.png)

Isso é um bug no módulo ou eu que não soube configurar isso corretamente?

**Comment by prestabr** [comment]
Bom Dia sarinalustosa,

Obrigado por utilizar o módulo oficial da PagSeguro em sua loja! :)

Aplicando o desconto você deve ver ele sinalizado no resumo do pedido, exemplo: 

![Screenshot at 2020-06-08 10-52-12](https://user-images.githubusercontent.com/7054224/84038285-23cb9100-a976-11ea-9129-e7b70746b191.png)

Para o caso de boleto bancário, se a sua loja estiver em modo debug alguns problemas podem ocorrer devido aos redirecionamentos.

Desativando Debug:

/* Debug only */
if (!defined('_PS_MODE_DEV_')) {
define('_PS_MODE_DEV_', **false**);
}

Atenciosamente,
Equipe PrestaBR

**Comment by sarinalustosa** [comment]
Olá, 

Obrigada pela resposta, como pode ver nenhum desconto foi aplicado:

![image](https://user-images.githubusercontent.com/31964035/84039302-73f72300-a977-11ea-8665-f4db7dee639b.png)

E minha loja não está em modo debug:

![image](https://user-images.githubusercontent.com/31964035/84039546-c20c2680-a977-11ea-9ea4-29bcd1c9a94a.png)

**Comment by prestabr** [comment]
Olá sarinalustosa,

Estamos fazendo alguns testes do nosso lado, mas não conseguimos reproduzir o problema:

![Screenshot at 2020-06-08 11-20-26](https://user-images.githubusercontent.com/7054224/84041346-19ab9180-a97a-11ea-88e8-6f4b2f255ef4.png)

![Screenshot at 2020-06-08 11-20-07](https://user-images.githubusercontent.com/7054224/84041363-1e704580-a97a-11ea-8570-e5ef8c9efe8c.png)

![Screenshot at 2020-06-08 11-19-52](https://user-images.githubusercontent.com/7054224/84041369-216b3600-a97a-11ea-8e1a-61c7d39b1e39.png)

Tenta limpar o cache da loja na tab "Desempenho", verifica se as permissões dos arquivos e diretórios estão ok (755 diretórios e 644 arquivos), confere também se existe alguma override de terceiro causando conflito.

Atenciosamente,
Equipe PrestaBR

**Comment by sarinalustosa** [comment]
Agora foi! Acho que era a cache:

![image](https://user-images.githubusercontent.com/31964035/84043018-2cbf6100-a97c-11ea-8c47-687b7173dc75.png)

Obrigada!

**Comment by prestabr** [comment]
Olá sarinalustosa,

Ótimo! Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
