### ISSUE TITLE
Módulo PagSeguropro prestashop 1.7.6.5

### ISSUE THREAD

**Issue by brazcomp** [pagseguro/prestashop#102]
Olá,

Estou implementando o módulo do PagSeguro no site prestashop 1.7.6.5 com PHP7.1.33, possiu certificado SSL do CPANEL, contudo não funciona o módulo. Já tentei com duas contas distintas do pagseguro e sem sucesso. Segui esses passos do link abaixo https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Após a checagem acima vá até a tela de Checkout da Loja, acesse o Inspetor de Elementos do Navegador pressionando “CTRL+Shift+i” ou F12.

Ao abrir o Inspetor de Elementos, clique na tab “Console” e verifique se estão presentes as seguintes informações:

SessionID
SenderHash
paymentMethods
installments
valorPedido
Com as 05 informações disponíveis no Console do Inspetor de Elementos do Navegador, significa que não houve problemas de conflitos interferindo no funcionamento do JavaScript do módulo, e a Loja está pronta para processar pagamentos.

Ao realizar o procedimento acima, não aparece as informações no console, apenas os erros:
Session ID: 4b4ff3270d3440f096ea72cd1bc051a4
10A cookie associated with a cross-site resource at was set without the SameSite attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with SameSite=None and Secure. You can review cookies in developer tools under Application>Storage>Cookies and see more details at and .
logo_pagseguro_mini_mobile.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
loading.gif:1 Failed to load resource: the server responded with a status of 404 (Not Found)
logo_pagseguro.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
pagseguropro.js:59 Uncaught TypeError: Cannot read property 'status' of undefined
at pagseguropro.js:59
at pagseguro.directpayment.js:1
(anonymous) @ pagseguropro.js:59
(anonymous) @ pagseguro.directpayment.js:1
pagseguropro.js:169 Object
pagseguropro.js:104 Object
DevTools failed to load SourceMap: Could not load content for chrome-extension://ndjpnladcallmjemlbaebfadecfhkepb/editor/config.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://ndjpnladcallmjemlbaebfadecfhkepb/editor/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://conceitoquadros.com.br/themes/core.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Aguardo um retorno.
Att,
Vander Braz

**Comment by prestabr** [comment]
Boa Tarde brazcomp,

Obrigado por utilizar o módulo oficial da PagSeguro!

O módulo depende essencialmente de JavaScript para funcionar corretamente e conseguir carregar a tela de checkout para posteriormente processar as transações com sucesso.

Eventuais problemas de programação JavaScript no Layout (Tema da sua loja), em módulo de terceiro ou na execução de Scripts externos podem ocasionar conflitos ou até o travamento de determinadas funcionalidades, que dependem exclusivamente do JavaScript para funcionar.

Aparentemente a sua loja tem muitos conflitos/travamentos de JavaScript. Estes conflitos sinalizados no seu Inspetor de Elementos estão relacionados ao módulo, mas não são originados por ele. Imagina que o JavaScript funciona dessa forma:

Processo A - arquivos .js do tema
Processo B - arquivos .js externos
Processo C - arquivos .js do módulo pagseguropro

Se algum conflito existir no processo A ou B o processo C não vai funcionar direito e vai apresentar problema.

Confere essas dicas:

**a)** Acessa as configurações do módulo e, verifica se a opção "Exibir parâmetros no Console do navegador?" está habilitada. Confere essas orientações: https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Esta opção é útil para nortear e auxiliar o trabalho técnico nas correções e melhorias da loja, facilitando a análise de eventuais problemas. Se você não tem conhecimento técnico o ideal é que procure a ajuda de um profissional.

**b)** Verifique se o token é de produção e o ambiente também;

**c)** Verifique se as tabelas do banco de dados "ps_pagseguropro" e "ps_pagseguropro_logs" estão corretamente instaladas;

**d)** Verifique se as permissões dos arquivos em sua hospedagem estão configuradas corretamente, o ideal é 755 para diretórios e 644 para arquivos.

**e)** Acesse no Back Office a tab "Parâmetros Avançados > Desempenho > CCC (COMBINAÇÃO, COMPRESSÃO E CACHE)".

Marque como "Não" a opção "Cache inteligente para JavaScript". Também limpe o cache no botão que fica no canto superior direito dessa tab, com o nome "Limpar cache".

É comum tem algum detalhe de JavaScript customizado no tema da loja, que não segue as melhores práticas de desenvolvimento, e acabam não suportanto as otmizações que o CCC proporcionam - gerando conflitos diversos e travamentos diversos.

**Importante:**

Para evitar problemas com o processamento do pagamento sugerimos que torne
obrigatório os seguintes campos no cadastro do cliente: cpf, endereço, numeral do endereço, bairro, cidade, estado, telefone ou celular.

Lembrando que o cpf é sempre obrigatório para vendas via cartão de crédito, independente se o cliente é PF ou PJ.

Atenciosamente,
Equipe PrestaBR
