### ISSUE TITLE
Checkout transparente

### ISSUE THREAD

**Issue by gugaalves** [pagseguro/prestashop#13]
E o checkout transparente?

**Comment by gabriellucius** [comment]
Olá @gugaalves o checkout transparente foi implementado na versão 2.2 do Módulo, caso queira conferir.

**Comment by silici0** [comment]
Não funciona a versão 2.2 com prestashop 1.6.1.11
Tem varios bugs nesses JS de checkout transparente, no meio do processo, escrevendo campos entra o loading, sai o loading, atrapalhando a digitação dos campos, no final do processo o pedido é criado mas não faz o envio para o pagseguro, ficando um pedido sem status!

**Comment by danielmaciel9** [comment]
cade o checkout trasnparente funcionando, jesus..

**Comment by guto32** [comment]
pagseguro checkout transparente ..... não consigo realizar, ele em modo de produção quando realizar uma simulaçao de venda teste .... lightbox funciona perfeitamente ...... a partir de uma solução Este probleminha ?!
