### ISSUE TITLE
Problemas com thirtybees

### ISSUE THREAD

**Issue by aykou** [pagseguro/prestashop#36]
## PrestaShopException  
**Class 'PagSeguroConfig' not found**  
 *at line* **201** *in file* `modules/pagseguro/features/notification/pagseguronotificationorderprestashop.php`  
```php  
196.        }
197.    
198.        private function createLog($e)
199.        {
200.            /** Retrieving configurated default charset */
201. =>         PagSeguroConfig::setApplicationCharset(Configuration::get('PAGSEGURO_CHARSET'));
202.    
203.            /** Retrieving configurated default log info */
204.            if (Configuration::get('PAGSEGURO_LOG_ACTIVE')) {
205.                PagSeguroConfig::activeLog(_PS_ROOT_DIR_ . Configuration::get('PAGSEGURO_LOG_FILELOCATION'));
206.            }
```  
- **PagSeguroNotificationOrderPrestashop->createLog** - [line `69` - `modules/pagseguro/features/notification/pagseguronotificationorderprestashop.php`]  
 - [1 Arguments]  
```php  
64.    
65.                if ($this->obj_transaction) {
66.                    $this->updateCms();
67.                }
68.            } catch (Exception $e) {
69. =>             $this->createLog($e->getMessage());
70.            }
71.    
72.        }
73.    
74.        /**
```  
```Argument [0]  
Invalid notification parameters.
```  
- **PagSeguroNotificationOrderPrestashop->postProcess** - [line `39` - `modules/pagseguro/controllers/front/notification.php`]  
 - [1 Arguments]  
```php  
34.    
35.        public function postProcess()
36.        {
37.            parent::postProcess();
38.            $pagNotification = new PagSeguroNotificationOrderPrestashop();
39. =>         $pagNotification->postProcess($_POST);
40.        }
41.    }
```  
```Argument [0]  
Array
(
)

```  
- **PagSeguroNotificationModuleFrontController->postProcess** - [line `379` - `classes/controller/Controller.php`]  
```php  
374.                if ($this->checkAccess()) {
375.                    if (!$this->content_only && ($this->display_header || (isset($this->className) && $this->className))) {
376.                        $this->setMedia();
377.                    }
378.    
379. =>                 $this->postProcess();
380.    
381.                    if (!empty($this->redirect_after)) {
382.                        $this->redirect();
383.                    }
384.    
```  
- **ControllerCore->run** - [line `742` - `classes/Dispatcher.php`]  
```php  
737.                if (isset($paramsHookActionDispatcher)) {
738.                    Hook::exec('actionDispatcher', $paramsHookActionDispatcher);
739.                }
740.    
741.                // Running controller
742. =>             $controller->run();
743.            } catch (PrestaShopException $e) {
744.                $e->displayMessage();
745.            }
746.        }
747.    
```  
- **DispatcherCore->dispatch** - [line `33` - `index.php`]  
```php  
28.     *  @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
29.     *  PrestaShop is an internationally registered trademark & property of PrestaShop SA
30.     */
31.    
32.    require(dirname(__FILE__).'/config/config.inc.php');
33. => Dispatcher::getInstance()->dispatch();
```

**Comment by s2it-moscou** [comment]
@aykou Bom dia, ainda está enfrentando esse problema ? Caso sim, pode me passar as versões dos módulos que está com esse erro ? Com esses dados da versão irei simular e caso necessário enviar para a Equipe de Desenvolvimento corrigir.

**Comment by aykou** [comment]
Versão 3.5.7 e muitas outras antes dessa, preciso que funcione em
https://thirtybees.com (prestashop melhorado).
Isso eu até corrigi, mas ainda está com problemas, não funciona.

*Atenciosamente,*

*Marcelo Livramento*
*lojaespacoanima.com.br <http://lojaespacoanima.com.br/>*
+55 (81) 9 9695-0870 / 9 9389-8030
Whatsapp (81) 9 9695-0870
molivramento@gmail.com / marcelo.livramento@anima.com.br



*"Ainda vejo o mundo com os olhos de criança, que só quer brincar e não
tanta responsa.** Mas a vida cobra serio e realmente não dá pra fugir!"*


Em 12 de fevereiro de 2018 09:22, s2it-moscou <notifications@github.com>
escreveu:

**Comment by s2it-moscou** [comment]
@aykou O Pagseguro não dá suporte ao módulo Thirty Bees https://thirtybees.com (prestashop melhorado), mas foi repassado para a Equipe do Pagseguro para avaliar a implementação do Plugin neste módulo !
