### ISSUE TITLE
Prestashop 1.7

### ISSUE THREAD

**Issue by sarment0** [pagseguro/prestashop#39]
Tem previsão para o prestashop 1.7?

**Comment by gabriellucius** [comment]
Olá @sarment0 
Iremos disponibilizar, mas ainda não temos uma previsão de data =/

**Comment by joesilver13** [comment]
Ola bom dia, gostaria de saber se tem previsão para o lançamento do modulo para o prestashop 1.7. Creio que seja o problema de muitas pessoas. sera que a versao anterior funciona no 1.7?

Obrigado

**Comment by jorgearamuni** [comment]
Também estou na espera ansiosa pelo módulo oficial para as versões 1.7 da Prestashop! Eu sugiro que haja uma MAIOR ATENÇÃO por parte do Pagseguro para com o lançamento RÁPIDO destes módulos, de forma a ACOMPANHAR as atualizações das plataformas de e-commerce. A Prestashop já está atualmente (na data em que escrevo) na versão 1.7.2.0, e no entanto só há o módulo oficial para a Prestashop 1.6.0.9. Ou seja, há um ATRASO MUITO GRANDE, e isto é RUIM PARA TODOS. Talvez o Pagseguro deva PAGAR MELHOR a sua equipe de desenvolvedores, de forma que eles possam AGIR EM CONJUNTO com os desenvolvedores das plataformas de e-commerce. A equipe do Pagseguro precisa agir de forma CONJUNTA com os desenvolvedores das plataformas. Esta distância enorme entre as datas de lançamento das atualizações das plataformas, com as datas de lançamento dos módulos, é RUIM PARA TODOS.

**Comment by sarment0** [comment]
@jorgearamuni Eu tive que comprar o módulo, pois se não iria perder dois clientes, a pagseguro não está acompanhando na mesma velocidade que o mercado está evoluindo, veja bem, prestashop foi lançado em março de 2017, mas já estava no beta desde o final de 2016, então houve tempo suficiente pra fazer o plugin, estamos no meio de agosto e até agora nada, por isso tive que comprar fora.

**Comment by jorgearamuni** [comment]
@sarment0 Preciso do módulo oficial para alguns projetos que tenho, por isto tenho de esperar o lançamento. Um módulo externo não serve para meus projetos. Temos de pressionar o Pagseguro para que tenha mais seriedade no desenvolvimento destes módulos de compatibilidade com as plataformas de ecommerce.

**Comment by vagkaefer** [comment]
Porra gente, vocês movimentam milhões de reais e ainda não tem a vergonha na cara de acompanhar o mercado? pelo amor de deus! Desisto de vocês, vou pra PayPal!

**Comment by vagkaefer** [comment]
Dai você vai ver os pull, e adivinha? Olhem o pull #34. Um usuário externo se prontificou a fazer o que a equipe não fez...

**Comment by adonaicanez** [comment]
Pelo jeito esse modulo para a versão 1.7 não vai sair mesmo. Uma empresa que vale bilhões de reais não paga um desenvolvedor para dar suporte para os clientes é sacanagem ....

**Comment by diegodigital** [comment]
previsão para o prestashop 1.7?

**Comment by 3W3R50N** [comment]
Alguma previsão de quando esse módulo será compatível com a versão 1.7.3.3 ? mais de 1 ano com esse projeto parado, tive problemas com pagseguro no magento e agora to tendo novamente no prestashop é uma falta de respeito com os usuários do módulo.

**Comment by jorgearamuni** [comment]
@3W3R50N Até agora não tive qualquer notícia! Um completo absurdo. Parece mesmo que o Pagseguro desistiu dos módulos para lojas virtuais. O melhor a fazer é usar as alternativas.

**Comment by 3W3R50N** [comment]
@jorgearamuni Como se não bastasse ainda tem gente que tem conhecimento se aproveita da situação compatibiliza um modulo e ao invés de compartilhar com a comunidade eles comercializam. Eu até entendo se esta for a única fonte de renda.

**Comment by jorgearamuni** [comment]
@3W3R50N Estou pensando em fazer um ABAIXO ASSINADO online, direcionado ao Pagseguro, para que dêem mais atenção ao desenvolvimento dos módulos para as lojas virtuais. O que vc acha?

**Comment by 3W3R50N** [comment]
@jorgearamuni É mais que necessário cria e posta o link aqui pra o pessoal assinar.

**Comment by amandaisabelalima** [comment]
Olá pessoal. O módulo oficial do PagSeguro para o PrestaShop 1.7.x já foi desenvolvido e está em homologação. Logo já vamos disponibilizar ela aqui no GitHub =)

**Comment by stefanoc1** [comment]
Boa tarde

Aguardo alguma posição do PagSeguro sobre o módulo para PrestaShop 1.7x, pois muitas lojas/usuários vão migrar para a concorrência...

**Comment by papalardo** [comment]
2 anos depois e cá estamos..
Se tivessem contratado um freelancer, já tinham terminado.
