### ISSUE TITLE
Erro 11035

### ISSUE THREAD

**Issue by PedroPASimoes** [pagseguro/prestashop#40]
Estou com o erro 11035 no modo padrão, e no modo lightbox e checkout transparente fica em um loading infinito mas nada é enviado ao pagseguro, apenas a loja contabiliza. O que posso fazer?

**Comment by felipebranco** [comment]
Boa tarde @PedroPASimoes pode me passar informações sobre qual versão do Prestashop você está usando simular o erro ?

**Comment by maarvvini** [comment]
@felipebranco @PedroPASimoes Resolveram esse problema? No meu estou tendo o mesmo problema, no final do checkout transparent onde tenho as 3 opções (Cartão, Debito ou Boleto), só funciona o Cartão, Boleto e Debito quando clica em concluir fica carregando infinitamente, gera o pedido no site porém não é redirecionado para a página de conclusão da compra, estou usando ps 1.6.1.6

**Comment by maarvvini** [comment]
???

**Comment by felipebranco** [comment]
@PedroPASimoes @maarvvini Simulei o problema relatado e realmente está ocorrendo o problema no Checkout Transparente em Boleto e Débito Online, será aberto para a equipe de desenvolvimento do Pagseguro corrigir. Obrigado pela contribuição

**Comment by felipebranco** [comment]
@PedroPASimoes  @maarvvini  Simulei o problema relatado e realmente está ocorrendo o problema no Checkout Transparente em Boleto e Débito Online, será aberto para a equipe de desenvolvimento do Pagseguro corrigir. Obrigado pela contribuição

**Comment by WebGF** [comment]
Bom dia estou tento um erro muito proximo. Quando o cliente chega a pagina de checkout ele entra em um loading infinito. Isso apenas ocorre quando o cliente esta logado.

**Comment by prestabr** [comment]
Bom Dia WebGF,

> Bom dia estou tento um erro muito proximo. Quando o cliente chega a pagina de checkout ele entra em um loading infinito. Isso apenas ocorre quando o cliente esta logado.

Está utilizando o módulo de Checkout Transparente? Se sim, por favor, confere este issue: https://github.com/pagseguro/prestashop/issues/49

Atenciosamente,
Equipe PrestaBR

**Comment by WebGF** [comment]
Bom dia, apenas para manter registrado, o problema foi resolvido ao atualizar meu modulo do checkout transparente com a ultima versão aqui do GITHUB. Obrigado pela paciencia.

**Comment by prestabr** [comment]
Olá WebGF,

Ótimo, obrigado pelo feedback. Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
