### ISSUE TITLE
Prestashop 1.7 - previsão

### ISSUE THREAD

**Issue by brunoramonalmeida** [pagseguro/prestashop#44]
Nada ainda? Mais de um ano não conseguiram desenvolver? Melhor dizer logo que não farão..ficar enganando os clientes

**Comment by rafaelvinicius** [comment]
Já completou 2 anos desde o lançamento da versão 1.7 do Prestashop, e até o momento não temos o módulo do PagSeguro.

**Comment by 3W3R50N** [comment]
Pelo visto não farão nada. eles já se sentem confortáveis com a situação.

**Comment by amandaisabelalima** [comment]
Olá @brunoramonalmeida, @rafaelvinicius  e @3W3R50N. O módulo do PagSeguro para a versão 1.7 do PrestaShop já foi desenvolvida e está em homologação. Logo será disponibilizada aqui no GitHub.
