### ISSUE TITLE
Transportar para Pagseguro o SKU (referencia do produto) e não título do produto

### ISSUE THREAD

**Issue by nilsonnq2019** [pagseguro/prestashop#46]
Olá,
Tenho instalado o módulo de pagamento Pagseguro no presta shop 1.6  eu gostaria que após o cliente efetuasse acompra fosse Transportado  para Pagseguro, o SKU (referência do produto) e não o  título do produto.

Eu tenho encontrado no código onde é possível efetuar as alterações mas tenho pouco conhecimento em programação por isso preciso de ajuda.:
/public_html/shop/modules/pagseguropro/views/templates/admin/detalhes.tpl

Resumindo ao invés de ser enviado o título do produto para o Pagseguro , enviar a Referência do mesmo.

Grato!

**Comment by prestabr** [comment]
Boa Tarde Nilson,

Só p/ organizar, encerrando esse issue duplicado, respondido aqui: https://github.com/pagseguro/prestashop/issues/45

Abraço.

Atenciosamente,
Equipe PrestaBR
