### ISSUE TITLE
Alguma previsão para a v1.7.x

### ISSUE THREAD

**Issue by 3W3R50N** [pagseguro/prestashop#47]
Bom dia, alguma previsão para a primeira release compatível com a versão 1.7.x ansioso para começar os testes pois tenho uma loja virtual pessoal esperando para abrir e não quero abrir na versão 1.6.x prefiro esperar o meio de pagamento compatível com a versão atual do prestashop.

Grato pela iniciativa.

**Comment by prestabr** [comment]
Boa Tarde 3W3R50N,

Tudo bem?

Obrigado pelo feedback e interesse no módulo oficial do PagSeguro! :)

O módulo para a versão 1.7.x está em nossa agenda! Ainda não temos uma data para o lançamento, mas será em breve. Vamos manter esse tópico aberto para te manter atualizado sobre essa data.

Abraço.

Atenciosamente,
Equipe PrestaBR

**Comment by rslanna** [comment]
> Boa Tarde 3W3R50N,
> 
> Tudo bem?
> 
> Obrigado pelo feedback e interesse no módulo oficial do PagSeguro! :)
> 
> O módulo para a versão 1.7.x está em nossa agenda! Ainda não temos uma data para o lançamento, mas será em breve. Vamos manter esse tópico aberto para te manter atualizado sobre essa data.
> 
> Abraço.
> 
> Atenciosamente,
> Equipe PrestaBR

na agenda desde 2017.
já estamos no prestashop 1.7.5, a promessa vem desde a versão 1.7.1.

**Comment by prestabr** [comment]
Boa Tarde Pessoal,

Tudo bem?

Agradecemos muito pelo interesse nos novos módulos oficiais do PagSeguro!

@rslanna assumimos recentemente o desenvolvimento dos módulos, no final de 2018. Estamos seguindo agenda focando no Checkout Transparente da 1.6, agora partimos para a 1.7.

A previsão para o lançamento do módulo na versão 1.7 é para Junho/2019, já devidamente homologado e pronto para operar em produção, com risco mínimo de bugs, no mesmo padrão de qualidade do módulo da 1.6.

Em paralelo, também estaremos lançando eventuais atualizações do múdulo da 1.6 aqui no Git.

Abraço.

Atenciosamente,
Equipe PrestaBR

**Comment by fernandocg30** [comment]
Olá, boa tarde! Preciso instalar com urgência o módulo para um cliente que possui versão 1.7... Estava pensando em adequar o módulo do 1.6 à nova versão. Existe alguma recomendação de vocês para que eu consiga fazer isso? Obrigado!

**Comment by prestabr** [comment]
Boa Tarde fernandocg30,

Obrigado pelo seu contato!

Não tem caminho fácil... O PS 1.6 é MVC e o 1.7 é Symfony mesclado com MVC.

O lançamento da 1.7 continua em nosso backlog para Junho/2019.

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Boa Tarde Pessoal,

Tudo bem?

Apenas um feedback... O Módulo está pronto, estamos em fase de testes e homologação. Ainda este mês (Junho) estaremos lançando o módulo por aqui.

Abraço.

Atenciosamente,
Equipe PrestaBR

**Comment by 3W3R50N** [comment]
Agradeço o feedback, estou ansioso para iniciar os testes.

Bom trabalho Equipe @PrestaBR

**Comment by cyrocostsolution** [comment]
Na expectativa, só falta isso pra lançar o site.

**Comment by prestabr** [comment]
Boa Tarde Pessoal,

Obrigado pela paciência de todos. Só estamos aguardando a fila do processo de homologação e a gente já solta o módulo aqui.

Atenciosamente,
Equipe PrestaBR

**Comment by Samuelsantos954** [comment]
O modulo foi lançado mas quando eu vou instalar o modulo, ele nao instala, não sei se estou fazer da forma errada... mas a forma q eu estou fazendo é a seguinte, eu baixo o arquivo aqui, e tento subir ela pro prestashop, e dar erro.

**Comment by Samuelsantos954** [comment]
se alguém ai puder me ajudar agradeço.

**Comment by LeandroMachado87** [comment]
Samuelsantos954, você tem o link para download da versão 1.7?

**Comment by prestabr** [comment]
Boa Tarde Pessoal,

Tudo bem?

Ainda não lançamos o módulo da versão 1.7 p/ checkout transparente. 

Samuelsantos954, os módulos oficiais do PagSeguro p/ PrestaShop são desenvolvidos pela PrestaBR e são lançados aqui no GitHub, o que você está utilizando não é oficial.

Já finalizamos o desenvolvimento do módulo da 1.7, já passamos pelo processo de homologação. Agora estamos trabalhando em uma loja piloto. Dentro de alguns dias vamos soltar para o público!

Agradecemos a enorme paciência de todos.

Atenciosamente,
Equipe PrestaBR

**Comment by Samuelsantos954** [comment]
> Boa Tarde Pessoal,
> 
> Tudo bem?
> 
> Ainda não lançamos o módulo da versão 1.7 p/ checkout transparente.
> 
> Samuelsantos954, os módulos oficiais do PagSeguro p/ PrestaShop são desenvolvidos pela PrestaBR e são lançados aqui no GitHub, o que você está utilizando não é oficial.
> 
> Já finalizamos o desenvolvimento do módulo da 1.7, já passamos pelo processo de homologação. Agora estamos trabalhando em uma loja piloto. Dentro de alguns dias vamos soltar para o público!
> 
> Agradecemos a enorme paciência de todos.
> 
> Atenciosamente,
> Equipe PrestaBR

Mas eu baixei o modulo aqui nesse site... vocês pode estar me enviando o link do modulo oficial?

**Comment by prestabr** [comment]
> > Boa Tarde Pessoal,
> > Tudo bem?
> > Ainda não lançamos o módulo da versão 1.7 p/ checkout transparente.
> > Samuelsantos954, os módulos oficiais do PagSeguro p/ PrestaShop são desenvolvidos pela PrestaBR e são lançados aqui no GitHub, o que você está utilizando não é oficial.
> > Já finalizamos o desenvolvimento do módulo da 1.7, já passamos pelo processo de homologação. Agora estamos trabalhando em uma loja piloto. Dentro de alguns dias vamos soltar para o público!
> > Agradecemos a enorme paciência de todos.
> > Atenciosamente,
> > Equipe PrestaBR
> 
> Mas eu baixei o modulo aqui nesse site... vocês pode estar me enviando o link do modulo oficial?

Boa Tarde Samuelsantos954,

Por equanto, aqui no Git só tem checkout transparente pra versão 1.6 da PrestaShop.

Módulo: https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro.

Download: https://github.com/pagseguro/prestashop/archive/master.zip

Se você tentar instalar esse módulo na sua loja PrestaShop versão 1.7 não vai dar certo, esse só funciona na versão 1.6.

Atenciosamente,
Equipe PrestaBR

**Comment by Samuelsantos954** [comment]
ah certo, Mas na mensagem anterior você disse que ja tinha finalizado o desenvolvimento do modulo da 1.7, mesmo que eu não encontre ela aq nesse site, quero saber em qual site encontro

**Comment by prestabr** [comment]
Olá Samuelsantos954,

Por favor, confere o histórico de mensagens aqui na página, tenta ler com calma desde o começo...

Por enquanto o módulo oficila na versão 1.7 não está disponível em lugar nenhum. Aqui é o canal oficial e recomenamos somente o módulo oficial. Fora daqui com solução de terceiro não temos como te orientar.

Quando o módulo estiver disponível voltamos aqui para avisar, ele estará disponível nesta área: https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente

Atenciosamente,
Equipe PrestaBR

**Comment by 3W3R50N** [comment]
Bom dia pessoal, como profissional da área entendo que previsão é algo complicado. más visto que vocês informaram que o módulo estava pronto e que estava em fase de homologação, gostaria que nos desse uma nova previsão, em consideração a muitos aqui que estão com seus projetos parados esperando apenas o módulo. 

Agradeço o esforço de todos envolvidos e me coloco a disposição para testar em minha loja já que não lancei ainda.

**Comment by prestabr** [comment]
Bom Dia Pessoal,

Agradecemos a paciência de todos! @3W3R50N e @Hodes, obrigado pela força!

O módulo de checkout transparente para a versão 1.7.x da PrestaShop está disponível: https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro

Estaremos mantendo o módulo sempre atualizado aqui no Git!

Desejamos Boas Vendas a todos! :)

Atenciosamente,
Equipe PrestaBR

**Comment by Samuelsantos954** [comment]
Após a checagem acima vá até a tela de Checkout da Loja, acesse o Inspetor de Elementos do Navegador pressionando “CTRL+Shift+i” ou F12.

Ao abrir o Inspetor de Elementos, clique na tab “Console” e verifique se estão presentes as seguintes informações:

SessionID
SenderHash
paymentMethods
installments
valorPedido
Com as 05 informações disponíveis no Console do Inspetor de Elementos do Navegador, significa que não houve problemas de conflitos interferindo no funcionamento do JavaScript do módulo, e a Loja está pronta para processar pagamentos.

A minha loja nao apareceu as 05 informações, o que faço pra resolver? Estar dando erro na hora de processar pagamentos.
