### ISSUE TITLE
GetInstallments - Parcelamento

### ISSUE THREAD

**Issue by arodel** [pagseguro/prestashop#48]
O valor que aparece no parcelamento por cartão de crédito é diferente dos parcelamento no site do PagSeguro. Quando o cliente compra parcelado ele consegue finalizar no site a compra mas ela não é processada pelo PagSeguro, e no log tem o retorno do erro.
 " <error>
    <code>53041</code>
    <message>installment value invalid value: xxx.xx</message> (onde xxx.xx é o valor da parcela)
  </error>"
Uso o checkout transparente do prestashop1.6

**Comment by prestabr** [comment]
Boa Tarde Arodel,

Obrigado pelo seu contato!

A API esa enfrentando instabilidades intermitentes e dificuldades com o processamento do getinstallments (mecanismo de parcelamento). O pessoal da área técnica já está trabalhando para normalizar os serviços.

Apenas para esclarecer, a lógica de funcionamento no módulo é essa:

"Quando o cliente acessa o checkout da loja o módulo envia para a API o valor total do pedido e aguarda o valor das parcelas para exibir para o cliente. Na sequência, quando o cliente clica em Pagar, o módulo envia para a API todos os dados relacionados ao pedido, incluindo o valor da parcela previamente informado pela API.

Se analizar os logs o retorno da API indica que o valor do parcelamento está incorreto, mas é a própria API que informa o valor da parcela.

Exemplo de resposta:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<errors>
  <error>
    <code>53041</code>
    <message>installment value invalid value: 40.73</message>
  </error>
</errors>
"

Caso surja alguma update na API, que exija modificações no módulo, nós estaremos lançando uma atualização por aqui.

Enquanto o problema não é resolvido na API, faz o seguinte...

Acessa o arquivo: /modules/pagseguropro/controllers/front/validation.php (https://github.com/pagseguro/prestashop/blob/master/1.6.x/checkout-transparente/pagseguropro/controllers/front/validation.php)

Descomenta a linha 94 e Comenta a linha 95:

Linha 94: //$this->retornoErroApi();
Linha 95: $this->criaPedidoErroApi();

Com esta alteração o módulo não irá criar o pedido na loja virtual caso surja problemas no getinstallments. E o cliente irá receber o alerta na tela de checkout para tentar realizar o pedido novamente.

Atenciosamente,
Equipe PrstaBR

**Comment by arodel** [comment]
Ok, muito obrigado pela rápida resposta.

Em sex, 3 de mai de 2019 às 15:38, PrestaBR <notifications@github.com>
escreveu:

**Comment by arodel** [comment]
Olá PrestaBR,

O problema com o getinstallments continua até agora, existe alguma previsão
para conserto da API? Com que área no PagSeguro temos que contatar?

No aguardo,
André

Em sáb, 4 de mai de 2019 às 07:24, Andre Rodel <andre@bonabessa.com.br>
escreveu:

**Comment by prestabr** [comment]
Boa Tarde arodel,

Desculpe a demora para retornar.

Você pode contactar o suporte técnico do PagSeguro para sinalizar esta questão neste link: https://faq.pagseguro.uol.com.br/

Abraço.

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Bom Dia arodel,

Tudo bem?

Lançamos uma update (v.1.1.3) no módulo para resolver a questão do getinstallments (parcelamento). Quando puder atualiza o módulo na sua loja...

Vamos fechar o ticket, qualquer problema é só postar de novo.

Abraço.

Atenciosamente,
Equipe PrestaBR

**Comment by arodel** [comment]
Boa tarde Equipe PrestaBR,

Fiz a atualização usando a v.1.1.3 porém o problema do getinstallments continua. Para ter certeza, também desinstalei todo o módulo, apaguei os arquivos e então reinstalei apenas a v.1.1.3 e mesmo assim continuou o problema do getinstallments.

Alguma sugestão de como proceder?

No aguardo,
Grato,

Arodel

**Comment by prestabr** [comment]
Boa Tarde arodel,

Obrigado pelo feedback.

Do nosso lado fizemos diversos testes e não conseguimos reproduzir o problema até o momento, mantemos o módulo em diversas lojas com alto volume de vendas.

Mas hoje a API está com alguma instabilidade, recebemos alguns feedbacks de dificuldades para os pedidos via Boleto.

Se puder, abre um chamado no canal https://faq.pagseguro.uol.com.br/ e solicita um feedback sobre a instabilidade e eventuais travamentos no getinstallmentes da API JS.

Abraço.

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Boa Tarde arodel,

Voltando na questão, temos apenas a sua demanda sobre o getinstallmentes. Pode ser algum problema pontual do seu lado, na loja, módulo ou hospedagem.

Se puder fornecer mais detalhes, acesso ao admin da loja e hospedagem, ftp/sql (ou cpanel), podemos encaminhar para um técnico analisar.

Abraço.

Atenciosamente,
Equipe PrestaBR
