### ISSUE TITLE
Lightbox para Prestashop 1.6 esta com problema no tamanho do token

### ISSUE THREAD

**Issue by EneiasPrado** [pagseguro/prestashop#50]
A versão 1.6 do litbox não foi atualizada para o token de tamanho 100, não estou conseguindo configurar devido a este problema...algo que possa fazer para mudar este problema ?

**Comment by tatianilima** [comment]
Mesmo problema aqui

**Comment by prestabr** [comment]
Boa Tarde Pessoal,

Tudo bem?

Atualizamos o módulo agora (v.2.2.1), é só copiar o módulo inteiro ou substituir esses 2 arquivos na loja:

https://github.com/pagseguro/prestashop/blob/master/1.6.x/lightbox-redirect/pagseguro/pagseguro.php
https://github.com/pagseguro/prestashop/blob/master/1.6.x/lightbox-redirect/pagseguro/views/templates/admin/settings.tpl

Abraço.

Atenciosamente,
Equipe PrestaBR
