### ISSUE TITLE
Status do pedido não é alterado quando Boleto

### ISSUE THREAD

**Issue by rafaelsilvabra** [pagseguro/prestashop#51]
Amigo, primeiramente obrigado pelo desenvolvimento do módulo.

Estou com o seguinte problema. Cliente que paga com cartao o status é alterado(liberado ou cancelado) normalmente porem quando o cliente escolhe Boleto não é  alterada o status.  Mas se clicar no pedido e aparece a informação de pago no final da página.

Podem ajudar?

![erro_status](https://user-images.githubusercontent.com/31866021/62707438-b94d6b80-b9c7-11e9-93dc-5744f35cdb03.jpg)

**Comment by prestabr** [comment]
Boa Tarde rafaelsilvabra,

Esse problema foi resolvido na versão mais recente do módulo, confere:

Changelog (no final da página): https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro

v.1.1.4

Fix Bug templateVars updateOrderStatus;
Fix Bug callback updateOrderStatus p/ Boleto Pendente (Status 2 - Aguardando Pgto);
Fix data_pedido (sql) p/ formato 24hs;
Add novo Logo do PagSeguro;

É só atualizar o módulo em sua loja, substitui os arquivos e depois limpa o cache na tab "Parâmetros Avançados > Desempenho".

As atualizações de status do boleto ocorrem sempre na madrugrada. Boas vendas!

Atenciosamente,
Equipe PrestaBR

**Comment by rafaelsilvabra** [comment]
Já estou usando a versão 1.1.4.
Fiz o seguinte. substitui os arquivos e fiz o procedimento de limpeza do cache.

Amanha retorno dando certo ou não.
Muito obrigad0.

**Comment by prestabr** [comment]
Olá rafaelsilvabra,

Perfeito, obrigado pelo feedback.

Se por acaso a sua hospedagem estiver trabalhando com firewall, libere a url de notificação do módulo: https://www.nomadasualoja.com.br/modules/pagseguropro/notification.php

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Olá rafaelsilvabra,

Identificamos um problema na update da v.1.1.4, acabamos de atualizar p/ a v.1.1.5.

Essa update se aplica ao arquivo: https://github.com/pagseguro/prestashop/blob/master/1.6.x/checkout-transparente/pagseguropro/notification.php

Por favor, faça o download do módulo novamente e repita a substituição dos arquivos e limpeza de cache em sua loja.

Qualquer problema ficamos à disposição.

Atenciosamente,
Equipe PrestaBR

**Comment by rafaelsilvabra** [comment]
Obrigado Equipe.

Já alterei os arquivos e irei verificar os pedidos e seus status.
Abs.

**Comment by prestabr** [comment]
Olá rafaelsilvabra,

Legal, obrigado! Por favor, posta aqui pra gente o resultado.

Abraço.

Atenciosamente,
Equipe PrestaBR

**Comment by rafaelsilvabra** [comment]
Problema resolvido.
Obrigado.

**Comment by casaud** [comment]
Olá!  Está com mesmo problema naversão 1.7 do prestashop.
Já foi solucionado para esta versão também? Grato!

**Comment by prestabr** [comment]
Bom Dia casaud,

> Olá! Está com mesmo problema na versão 1.7 do prestashop.
> Já foi solucionado para esta versão também?
> 
> E na página de redirecionamento do pagseguro, devo adicionar o endereço https://otakuanimes.com.br/modules/pagseguropro/notification.php ?
> 
> Grato!

Este problema afetava até a versão v.1.1.4 da 1.6, corrigido na v.1.1.5, hoje está na v.1.1.8.

O módulo da versão 1.7 do Checkout Transparente já foi lançado herdando a solução do problema identificado na verão 1.6.

A página de redirecionamento não fica no arquivo notification.php, o arquivo também não precisa de alterações e ou correções.

Faça algumas verificações em sua loja/hospedagem:

- Se você atualizou a versão da PrestaShop, da 1.6 pra 1.7, e já tinha o módulo instalado, confere se todos os arquivos foram substituídos corretamente pelos da 1.7;
- Confere se as permissões dos arquivos em sua hospedagem estão ok;
- Verifica se o arquivo está exatamente igual: https://github.com/pagseguro/prestashop/blob/master/1.7.x/checkout-transparente/pagseguropro/notification.php
- Se tiver algum firewall configurado de modo automatizado, add a url na whitelist: https://otakuanimes.com.br/modules/pagseguropro/notification.php

Atenciosamente,
Equipe PrestaBR

**Comment by casaud** [comment]
Vou testar! Muito Obrigado!
