### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by carlosvolp** [pagseguro/prestashop#54]
Boa tarde, ao confirmar a compra aparece esse erro, e lightbox não abre porem o cliente recebe email dizendo que compra foi efetuada.

Erro:
![Captura de Tela 2019-09-02 às 14 20 20](https://user-images.githubusercontent.com/4720895/64128444-f8839800-cd8c-11e9-84bb-a95137211e8a.png)

VM592:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.n.parseJSON (jquery-1.11.0.min.js:4)
    at Function.e.parseJSON (jquery-migrate-1.2.1.min.js:2)
    at Object.success (payment:414)
    at j (jquery-1.11.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.min.js:2)
    at x (jquery-1.11.0.min.js:4)
    at XMLHttpRequest.b (jquery-1.11.0.min.js:4)

Alguem pode me ajudar?

**Comment by prestabr** [comment]
Boa Tarde carlosvolp,

Este erro é genérico, pode ser conflito de JavaScript na tela de checkout da sua loja. Deixar o debug da PrestaShop ativo com a loja em produção também pode causar problemas.

Já tentou desativar?

/config/defines.inc.php
/* Debug only */
if (!defined('_PS_MODE_DEV_')) {
define('_PS_MODE_DEV_', **false**);
}

Verifica também se o módulo está atualizado, a versão atual é a 2.2.1: https://github.com/pagseguro/prestashop/tree/master/1.6.x/lightbox-redirect/pagseguro

Você conhece o módulo de checkout transparente? Esse tipo de chekcout pode otimizar muito as vendas na sua loja: https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro

Atenciosamente,
Equipe PrestaBR
