### ISSUE TITLE
Unknown web session id

### ISSUE THREAD

**Issue by murilomation** [pagseguro/prestashop#55]
Bom dia,

estou com um erro ao escolher a forma de pagamento.
Prestashop 1.7.5.2

O que pode ser ?

Grato,

![Screenshot_230](https://user-images.githubusercontent.com/54901717/64343757-7fba5100-cfc3-11e9-91eb-695aa5d01584.png)

**Comment by Hodes** [comment]
Opa, tive este problema quando o SSL não estava configurado.

**Comment by murilomation** [comment]
aparentemente tudo ok com SSL, o certificado está válido no navegador.

**Comment by Hodes** [comment]
Habilitou o SSL no prestashop ? 
Ex: https://www.hostinger.com/tutorials/how-to-add-ssl-to-prestashop

**Comment by murilomation** [comment]
Obrigado pela ajuda Hodes,
Está tudo habilitado, já verifiquei também na Hostgator.
Porém esse erro persiste.

![Screenshot_236](https://user-images.githubusercontent.com/54901717/64346968-7f24b900-cfc9-11e9-808d-c98f3c679a88.png)
![Screenshot_235](https://user-images.githubusercontent.com/54901717/64346969-7f24b900-cfc9-11e9-96c6-d49b3ae9a12b.png)

**Comment by prestabr** [comment]
Boa Tarde Pessoal,

@Hodes, obrigado pelo help! :)

@murilomation, esse erro indica que o módulo não conseguiu processar o JavaScript para iniciar uma sessão no PagSeguro. Na grande maioria das vezes esse problema ocorre por algum travamento de JavaScript na tela de Checkout da loja.

Eventuais problemas de programação JavaScript ou a execução de Scripts externos no Layout
podem ocasionar conflitos ou até o travamento de determinadas funcionalidades que
dependem exclusivamente do JavaScript para funcionar.

Faça alguns testes:

a) Verifique se o token é de produção e o ambiente também;

b) Verifique se as tabelas do banco de dados "ps_pagseguropro" e "ps_pagseguropro_logs" estão corretamente instaladas;

c) Acesse no Back Office a tab “Parâmetros Avançados > Desempenho > CCC (COMBINAÇÃO, COMPRESSÃO E CACHE)”.

Marque as opções “Cache inteligente para JavaScript”, “Comprimir JavaScript inline em
HTML” e “Mover o JavaScript para o final” como Não. Também limpe o cache no botão que fica no canto superior direito dessa tab, com o nome "Limpar cache".

É comum tem algum detalhe de JavaScript customizado no tema da loja, que não segue as melhores práticas de desenvolvimento, e acabam não suportanto as otmizações que o CCC proporcionam - gerando conflitos diversos.

d) Acessa as configurações do módulo e, verifica se a opção "Exibir parâmetros no Console do navegador?" está habilitada. Confere essas orientações: https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro

Atenciosamente,
Equipe PrestaBR

**Comment by murilomation** [comment]
Resolvido, muito obrigado pela ajuda.

**Comment by miqueiasazevedo** [comment]
> Resolvido, muito obrigado pela ajuda.

@murilomation , qual foi a solução no seu caso?
