### ISSUE TITLE
Atualização módulo

### ISSUE THREAD

**Issue by murilomation** [pagseguro/prestashop#56]
Bom dia,

qual a melhor forma de atualizar o módulo ?

Desabilitar, excluir e instalar de novo ?

Grato

**Comment by prestabr** [comment]
Bom Dia murilomation,

É simples, tem mais de uma forma de atualizar, você pode testar:

Na PS 1.6.x: 
Sobreescreve todos os arquivos no FTP da sua loja em /modules/pagseguropro/, na sequência acessa o backoffice e clica na tab "Módulos > Módulos e Serviços", pesquisa pelo módulo e confere que já está atualizado.

Na PS 1.7.x: 
Sobreescreve todos os arquivos no FTP da sua loja em /modules/pagseguropro/, na sequência acessa o backoffice e clica na tab "Módulos > Module Manager", pesquisa pelo módulo e clica no botão "Upgrade", pronto o módulo está atualizado. Você pode acessar novamente a tab "Module Manager" para visualizar a nova versão. 
Outra opção mais simples é seguir o passo-a-passo de instalação que também serve pra atualização: https://github.com/pagseguro/prestashop#instala%C3%A7%C3%A3o---prestashop-17x

Abraço.

Atenciosamente,
Equipe PrestaBR

**Comment by murilomation** [comment]
Muito obrigado
