### ISSUE TITLE
Checkout Transparente - PS 1.7.x - Não libera a tela de checkout para o pagamento

### ISSUE THREAD

**Issue by Samuelsantos954** [pagseguro/prestashop#57]
Após a checagem acima vá até a tela de Checkout da Loja, acesse o Inspetor de Elementos do Navegador pressionando “CTRL+Shift+i” ou F12.

Ao abrir o Inspetor de Elementos, clique na tab “Console” e verifique se estão presentes as seguintes informações:

SessionID
SenderHash
paymentMethods
installments
valorPedido
Com as 05 informações disponíveis no Console do Inspetor de Elementos do Navegador, significa que não houve problemas de conflitos interferindo no funcionamento do JavaScript do módulo, e a Loja está pronta para processar pagamentos.

A minha loja nao apareceu as 05 informações, o que faço pra resolver? Estar dando erro na hora de processar pagamentos.

**Comment by prestabr** [comment]
Boa Noite Samuelsantos954,

Na grande maioria das vezes esse problema ocorre por algum travamento de JavaScript na tela de Checkout da loja. É comum tem algum detalhe de JavaScript customizado no tema (layout), que não segue as melhores práticas de desenvolvimento, e acabam gerando conflitos diversos.

Faça alguns testes:

a) Verifique se o token é de produção e o ambiente também;

b) Verifique se as tabelas do banco de dados "ps_pagseguropro" e "ps_pagseguropro_logs" estão corretamente instaladas conforme o arquivo modelo: https://github.com/pagseguro/prestashop/blob/master/1.7.x/checkout-transparente/pagseguropro/sql/install.php

c) Acesse no Back Office a tab “Parâmetros Avançados > Desempenho > CCC (COMBINAÇÃO, COMPRESSÃO E CACHE)”.

Marque as opções “Cache inteligente para JavaScript”, “Comprimir JavaScript inline em
HTML” e “Mover o JavaScript para o final” como Não. Também limpe o cache no botão que fica no canto superior direito dessa tab, com o nome "Limpar cache".

d) Utilizando a PrestaShop 1.7, acesse no Back Office a tab "Pagamento > Preferências > Restrições de transportadora" e verifique se as transportadoras estão vinculadas à forma de pagamento.

Não conseguindo resolver, por favor, posta um print do console do seu navegador na tela de checkout.

Atenciosamente,
Equipe PrestaBR
