### ISSUE TITLE
Forma de pagamento temporariamente indisponível.

### ISSUE THREAD

**Issue by xworx** [pagseguro/prestashop#58]
Prezados,

Ao tentar processar o pagamento tenho o erro: **Forma de pagamento temporariamente indisponível. Por favor, tente novamente ou escolha outra forma de pagamento.** Habilitei boleto e cartão de crédito e em ambos o mesmo erro. Estou usando a versão 1.7.5.2 com o tema original e limpa, sem outros módulos. Verifiquei as orientações da documentação e também dos outros posts e está tudo aparentemente correto, verifiquei token, tabelas, CCC, etc.

O que pode ser?

Obrigado
![Captura de Tela 2019-09-29 às 19 47 25](https://user-images.githubusercontent.com/50961677/65841244-c8c9a080-e2f6-11e9-8d9e-89856eb25a23.png)
![Captura de Tela 2019-09-29 às 19 45 58](https://user-images.githubusercontent.com/50961677/65841245-c8c9a080-e2f6-11e9-9c82-6dea942e904a.png)
![x](https://user-images.githubusercontent.com/50961677/65841261-eac32300-e2f6-11e9-9c90-6298646007b6.png)

**Comment by prestabr** [comment]
Bom Dia xworx,

Obrigado pelos detalhes e por confirmar o funcionamento no Front.

Este problema costuma ocorrer quando o cliente (comprador) tem a conta com algum tipo de bloqueio lá no PagsSguro (cpf ou e-mail de cadastro). Neste caso é preciso orientar o cliente a criar outra conta na loja virtual (com outros dados de cadastro) ou solicitar que ele entre em contato com o PagSeguro para ele verificar as pendências na conta dele.

Nos seus testes, se você estiver tentando comprar com a mesma conta da integração (cpf ou e-mail de cadastro) não vai dar certo. O titular da conta não pode fazer pagamentos para ele mesmo via checkout transparente.

Verifique estes detalhes e tente fazer novos testes, ficamos à disposição.

Atenciosamente,
Equipe PrestaBR

**Comment by xworx** [comment]
Boa tarde PrestaBR,

Agradeço a atenção e a rapidez na resposta.

Acredito que o problema era o campo UF que não estava passando ("shippingAddressState": null,) minha loja estava configurada com o formato de formulário de endereço padrão sem o estado (State:iso_code). Corrigido isso funcionou com o mesmo cadastro e-mail/cpf que antes apresentava o erro.

Obrigado!

**Comment by prestabr** [comment]
Olá xworx,

Ótimo, muito obrigado pelo feedback!  Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR

**Comment by johnnyvaz1** [comment]
Por favor, onde que habilita para o cadastro de Estado ser obrigatório no registro de novos clientes?

**Comment by prestabr** [comment]
Boa Tarde johnnyvaz1,

Na PrestaShop **1.6**: Localização > Países

![Screenshot at 2019-10-22 12-38-43](https://user-images.githubusercontent.com/7054224/67303692-2ce01e80-f4c9-11e9-95e2-4e3662a6228e.png)

![Screenshot at 2019-10-22 12-39-16](https://user-images.githubusercontent.com/7054224/67303730-3a95a400-f4c9-11e9-84b9-86b4ffe420dc.png)
_Marca a opção "contém estados" como sim._

Na PrestaShop **1.7**: Internacional > Localizações (Tab Países)

![Screenshot at 2019-10-22 12-42-03](https://user-images.githubusercontent.com/7054224/67304018-9fe99500-f4c9-11e9-876a-87423d606996.png)

![Screenshot at 2019-10-22 12-42-32](https://user-images.githubusercontent.com/7054224/67304035-a546df80-f4c9-11e9-8553-d09f3586c8dd.png)
_Marca a opção "contém estados" como sim._

Atenciosamente,
Equipe PrestaBR

**Comment by luizricardofrancisco** [comment]
olá o meu não da certo, já coloquei estado ja mudei de pessoa para tentar comprar e nada, não sei mais onde arrumar, pois o pagseguro fala que testou e esta tudo correto... mais eu nem ninguém consigui comprar!!

**Comment by wesleifelix** [comment]
Estou com um erro estranho 3 compras foram aprovadas dentro do pagseguro porém o módulo não criou as vendas dentro do presta, e olhando os log o pagseguro devolve a notificação e fica no log como erro ao atualizar banco de dados, pq a venda não existe no presta.

**Comment by prestabr** [comment]
Boa Tarde wesleifelix,

Obrigado por utilizar o módulo oficial da PagSeguro em sua loja! :)

Confere essa dica de como verificar os logs e localizar a resposta correta da API: #75 (comment) (Leia com calma...)

Se você está recebendo a resposta OK, e o pedido não está sendo criado, talvez exista alguma lentidão na hospedagem ou o produto esteja com algum problema de cadastro/configuração.

Confere também se o seu módulo está atualizado, se os arquivos foram sobreescritos corretamente e se as permissões das pastas e arquivos estão corretas e aplicadas de forma recursiva (755 pastas e 644 diretórios).

Atenciosamente,
Equipe PrestaBR

**Comment by wesleifelix** [comment]
Obrigado por entrar em contato, não tem problemas com o servidor é uma questão estranha, foram 150 pedidos hoje e em 2 deles ele fez todas as requisições com o PagSeguro inclusive os Logs foram salvos, porém o módulo não transformou o carrinho em pedido, ficou como carrinho.
A questão é não seria prudente transformar o carrinho em pedido antes de enviar para o PagSeguro ao invés de fazer o contrário.

**Comment by prestabr** [comment]
Olá luizricardofrancisco,

> olá o meu não da certo, já coloquei estado ja mudei de pessoa para tentar comprar e nada, não sei mais onde arrumar, pois o pagseguro fala que testou e esta tudo correto... mais eu nem ninguém consigui comprar!!

Conseguiu resolver? O módulo está funcional em sua loja?

Como verificar se a sua integração está funcional:

PS 1.6: https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

PS 1.7: https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Acessando a área de Logs do módulo:

PS 1.6: https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#7---registro-de-transa%C3%A7%C3%B5es--gerenciamento-de-logs

PS 1.7: https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#7---registro-de-transa%C3%A7%C3%B5es--gerenciamento-de-logs

Ao acessar, confere como verificar os logs e localizar a resposta da API: #75 (comment) (Leia com calma...)

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Olá wesleifelix,

> Obrigado por entrar em contato, não tem problemas com o servidor é uma questão estranha, foram 150 pedidos hoje e em 2 deles ele fez todas as requisições com o PagSeguro inclusive os Logs foram salvos, porém o módulo não transformou o carrinho em pedido, ficou como carrinho.
> A questão é não seria prudente transformar o carrinho em pedido antes de enviar para o PagSeguro ao invés de fazer o contrário.

O carrinho de compras só é transformado em pedido após a confirmação do processamento do lado da API, este é o padrão de funcionamento do módulo de checkout transparente.

Este problema é bastante incomum, aparentemente indica algo do lado da loja virtual ou hospedagem. Talvez possa ser até um travamento ou breve indisponibilidade temporária na API.

Nestes casos, sugerimos que você localize o carrinho do cliente na loja virtual e crie o pedido manualmente. Dessa forma o cliente não precisa tentar comprar de novo e a loja consegue manter o controle do pedido normalmente.

Atenciosamente,
Equipe PrestaBR

**Comment by wesleifelix** [comment]
OK, após essa resposta, prefiro alterar, o módulo para criar o pedido, mesmo perdendo o carrinho depois, pois com volumes alto de pedido, pode virar um grande problema.
Ter 2 pedidos hoje que com este e problema e um 1 na sexta. 
Quando um cliente entra em contato é fácil solucionar mas ficar analisando todas as aprovações fica inviável.

**Comment by prestabr** [comment]
Olá wesleifelix,

Não recomendamos alterar o core do módulo, a menos que você saiba exatamente o que esteja fazendo. Ter 2 pedidos aleatórios, que parece ser a primeira vez que ocorre, em meio à 150/dia, parece ser uma contingência e modificar o módulo por conta disso não parece ser uma boa ideia.

Lembrando que o módulo é open-source e você tem total autonomia para adaptar e customizar como quiser.

Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR

**Comment by xworx** [comment]
Olá Pessoal,

Eu utilizo o módulo do Mercado Pago e quando ativo o PagSeguro, na etapa final, no topo da loja aparece a seguinte mensagem:

Notice: Undefined property: Address::$numend in /home/hostex/public_html/minhaloja.com.br/modules/pagseguropro/pagseguropro.php on line 282

Notice: Undefined property: Address::$compl in /home/hostex/public_html/minhaloja.com.br/modules/pagseguropro/pagseguropro.php on line 283

Se eu desativo o módulo do Mercado Pago essa mensagem não aparece, mas preciso usar os dois  juntos.

Obrigado

**Comment by prestabr** [comment]
Boa Noite xworx,

Já vimos algumas lojas utilizando as duas integrações simultâneamente. Mas é muito difícil apontar a origem do problema em sua loja porque é preciso levar em considerações enventuais customizações de layout, core, override, além de módulos de terceiro.

De qualquer forma, recomendamos que você opte por apenas uma das integrações. Optando pelo PagSeguro você tem a certeza de contar com updates regulares, melhorias e aprimoramentos constantes, além de suporte técnico especializado, rápido e ágil de alto nível técnico.

Se você tiver um fluxo de venda maior do que 50-100k ou mais por mês você pode negociar as taxas com o PagSeguro!

Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR

**Comment by xworx** [comment]
Boa tarde,

O tema é padrão nessa loja, versão 1.6

Utilizava nessa loja somente o PagSeguro, no entanto ultimamente vários clientes não tiveram suas transações aprovadas, direcionadas para o Mercado Pago todos foram aprovados. Fiz um teste com meu cartão através do módulo e não foi aprovada, em seguida fiz a mesma transação digitada no app do PagSeguro e foi aprovada.

Por garantia deixaria as duas opções mas como aparece esse aviso no topo da loja vamos desativar o PagSeguro e utilizar somente o Mercado Pago.

Agradeço a atenção

**Comment by prestabr** [comment]
Boa Tarde xworx,

> Boa tarde,
> 
> O tema é padrão nessa loja, versão 1.6
> 
> Utilizava nessa loja somente o PagSeguro, no entanto ultimamente vários clientes não tiveram suas transações aprovadas, direcionadas para o Mercado Pago todos foram aprovados. Fiz um teste com meu cartão através do módulo e não foi aprovada, em seguida fiz a mesma transação digitada no app do PagSeguro e foi aprovada.
> 
> Por garantia deixaria as duas opções mas como aparece esse aviso no topo da loja vamos desativar o PagSeguro e utilizar somente o Mercado Pago.
> 
> Agradeço a atenção

A questão do tema ser padrão ou não mencionamos apenas como referência, para que você consiga verificar se a sua integração está funcional na tela de checkout, livre de conflitos de JavaScript.

Verificando se está funcional:

PS 1.6: https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

PS 1.7: https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Estando funcional significa que o módulo está pronto para processar os pedidos na tela de checkout. Caso ocorra alguma dificuldade com a mensagem "_Forma de pagamento temporáriamente indisponível_", é só conferir a área de Logs do módulo para identificar o porque a transação não foi processada.

Na maioria dos casos é porque tem algum dado ausente no cadastro do cliente, que não foi tratado anteriormente na tela de cadastro da loja. Você pode conferir os campos obrigatórios no cadastro do cliente acessando "Clientes > Endereços > Definir os campos obrigatórios para esta seção". 

O ideal é ter estas informações como obrigatórias: cpf, endereço, numeral do endereço, bairro, cidade, estado, telefone ou celular. Lembrando que os pagamentos via cartão de crédito exigem o CPF vinculado, independete se é PF ou PJ.

Confere como verificar os logs e localizar a resposta da API, identificando o porque a transação não foi processada: https://github.com/pagseguro/prestashop/issues/75#issuecomment-567057058 (Leia com calma, leitura simples e rápida)

Estes detalhes devem resolver o seu problema de integração, permitindo tabalhar somente com a PagSeguro. Caso tenha alguma dificuldade é só postar os detalhes pra gente analisar pra você.

Atenciosamente,
Equipe PrestaBR

**Comment by brazcomp** [comment]
Olá,

Estou implementando o módulo do PagSeguro no site prestashop 1.7.6.5 com PHP7.1.33, possiu certificado SSL do CPANEL, contudo não funciona o módulo. Já tentei com duas contas distintas do pagseguro e sem sucesso. Segui esses passos do link abaixo https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Após a checagem acima vá até a tela de Checkout da Loja, acesse o Inspetor de Elementos do Navegador pressionando “CTRL+Shift+i” ou F12.

Ao abrir o Inspetor de Elementos, clique na tab “Console” e verifique se estão presentes as seguintes informações:

SessionID
SenderHash
paymentMethods
installments
valorPedido
Com as 05 informações disponíveis no Console do Inspetor de Elementos do Navegador, significa que não houve problemas de conflitos interferindo no funcionamento do JavaScript do módulo, e a Loja está pronta para processar pagamentos.

Ao realizar o procedimento acima, não aparece as informações no console, apenas os erros:
Session ID: 4b4ff3270d3440f096ea72cd1bc051a4
10A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
logo_pagseguro_mini_mobile.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
loading.gif:1 Failed to load resource: the server responded with a status of 404 (Not Found)
logo_pagseguro.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
pagseguropro.js:59 Uncaught TypeError: Cannot read property 'status' of undefined
    at pagseguropro.js:59
    at pagseguro.directpayment.js:1
(anonymous) @ pagseguropro.js:59
(anonymous) @ pagseguro.directpayment.js:1
pagseguropro.js:169 Object
pagseguropro.js:104 Object
DevTools failed to load SourceMap: Could not load content for chrome-extension://ndjpnladcallmjemlbaebfadecfhkepb/editor/config.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://ndjpnladcallmjemlbaebfadecfhkepb/editor/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://conceitoquadros.com.br/themes/core.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Aguardo um retorno.
Att,
Vander Braz
