### ISSUE TITLE
Repagamento

### ISSUE THREAD

**Issue by xworx** [pagseguro/prestashop#59]
Prezados,

O módulo possui a opção de repagamento? No painel de controle do cliente na loja há opção de refazer a transação que não foi finalizada ou rejeitada, bem como no caso de boleto se gerar a segunda via?

Obrigado

**Comment by prestabr** [comment]
Olá xworx,

Não existe essa opção no módulo de checkout transparente. O PagSeguro oferece o "Pagamento Recorrente" em outra API, diferente da que processa o checkout transparente, com outras regras e detalhes. Mas temos planos, pra 2020, de desenvolver um módulo somente para este segmento. Anotamos o seu pedido também...! :)

Sobre o boleto, sim é possível gerar segunda via entre outros detalhes. Você pode conferir na documentação como o Recorrente funciona: https://dev.pagseguro.uol.com.br/docs/introdu%C3%A7%C3%A3o-12#retentativa-de-pagamento

Atenciosamente,
Equipe PrestaBR
