### ISSUE TITLE
Erro '0' na tela de pagamentos

### ISSUE THREAD

**Issue by silviots** [pagseguro/prestashop#60]
Fiz todos os procedimentos conforme orientação do manual
mas apresenta erro "0" no lugar que deveria aparecer o pagseguro transparente
segue imagens das telas e erro.
https://www.dibambinni.com.br/img/pagseguro/erro.jpg
https://www.dibambinni.com.br/img/pagseguro/erro-01.jpg
gostaria de uma luz para achar o que possa estar impedindo o correto funcionamento do modulo
segue demais telas:
https://www.dibambinni.com.br/img/pagseguro/logs.jpg
https://www.dibambinni.com.br/img/pagseguro/tela-pagamento-01.jpg
https://www.dibambinni.com.br/img/pagseguro/tela-pagamento-02.jpg
https://www.dibambinni.com.br/img/pagseguro/tela-pagamento-03.jpg
https://www.dibambinni.com.br/img/pagseguro/CCC.jpg

Estou usando prestashop 1.7.6
 tema original e limpa, sem outros módulos. Verifiquei as orientações da documentação e também dos outros posts e está tudo aparentemente correto, verifiquei token, tabelas, CCC, etc.

**Comment by prestabr** [comment]
Boa Tarde silviots,

Visualizando os prints, o módulo não chega a ser carregado na tela de checkout. Utilizando a PrestaShop 1.7, acesse no Back Office a tab "Pagamento > Preferências > Restrições de transportadora" e verifique se as transportadoras estão vinculadas à forma de pagamento.

Qualquer dúvida ficamos à disposição.

Atenciosamente,
Equipe PrestaBR

**Comment by silviots** [comment]
Vou fazer isso desde já grato pelo retorno rápido

**Comment by silviots** [comment]
Exatamente na mosca perfeito!!!
resolvido essa etapa agora vou testar o restante mais uma vez grato pelo retorno rápido e parabens
pelo trabalho

**Comment by silviots** [comment]
solucionado

**Comment by prestabr** [comment]
Oi silviots,

Obrigado pelo feedback, Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
