### ISSUE TITLE
Falha ao carregar o recurso: o servidor respondeu com um status de 499

### ISSUE THREAD

**Issue by silviots** [pagseguro/prestashop#61]
Falha ao carregar o recurso: o servidor respondeu com um status de 499
segue tela de erro:
https://www.dibambinni.com.br/img/pagseguro/erro-02.jpg

estou utilizando prestashop 1.7.6

**Comment by prestabr** [comment]
Boa Tarde silviots,

Essa linha sinalizada no print com o status de 499 não faz parte do módulo ou do PagSeguro. Isto está relacionado à Google Analytics... https://developers.google.com/analytics/resources/concepts/gaConceptsTrackingOverview?hl=pt-br

Sobre a forma de pagamento temporáriamente indisponível, por favor, confere este post: https://github.com/pagseguro/prestashop/issues/58

Atenciosamente,
Equipe PrestaBR

**Comment by silviots** [comment]
ok vou fazer os testes desde já grato mais uma vez pelo retorno rápido

**Comment by silviots** [comment]
Ok resolvido analisei o log no gerenciador de log apontou campo district ou bairro em como null
foi só ajustar e pronto funcionando desde já grato pelo retorno e para os que poderão passar por isso sempre é bom olhar com calma o log e o retorno que está na tabela log no banco de dados me ajudou muito e contar também com o suporte do pessoal da prestaBR muito rápidos e prestativos

**Comment by prestabr** [comment]
Oi silviots,

Muito obrigado pelo feedback, Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
