### ISSUE TITLE
Servidor retornando 401 em todos os pagamentos (Email e Token estão corretos)

### ISSUE THREAD

**Issue by alfonsoalexandre** [pagseguro/prestashop#62]
Integrei uma loja virtual de um cliente em Prestashop 1.7 com o modulo do Pagseguro transparente checkout.
No entanto, mesmo apos revisar diversas vezes o email e o token do cliente, no momento de finalizar o pagamento no site dá o erro: 
![image](https://user-images.githubusercontent.com/56411572/66600909-0642ef00-eb7d-11e9-9853-302e4756fb4e.png)
Se o ambiente estiver em produção redireciona para este erro:
![image](https://user-images.githubusercontent.com/56411572/66601050-59b53d00-eb7d-11e9-8ebf-3c54d376a60a.png)
E apos preencher o boleto e clicar em finalizar:
![image](https://user-images.githubusercontent.com/56411572/66601084-6e91d080-eb7d-11e9-871e-2db95e19dd38.png)
Todos os logs estão assim:
![image](https://user-images.githubusercontent.com/56411572/66601125-849f9100-eb7d-11e9-9dec-b93bdfd2d2cb.png)

**Comment by prestabr** [comment]
Boa Noite alfonsoalexandre,

Obrigado por utilizar o módulo oficial em seus projetos! :)

Confere algumas dicas para solucionar esses problemas:

> Integrei uma loja virtual de um cliente em Prestashop 1.7 com o modulo do Pagseguro transparente checkout.
> No entanto, mesmo apos revisar diversas vezes o email e o token do cliente, no momento de finalizar o pagamento no site dá o erro:
> ![image](https://user-images.githubusercontent.com/56411572/66600909-0642ef00-eb7d-11e9-9853-302e4756fb4e.png)

Provavelmente causado pelo mesmo problema do último print (shippingAddressState está como "null").
Por favor, veja este issue: https://github.com/pagseguro/prestashop/issues/58

> Se o ambiente estiver em produção redireciona para este erro:
> ![image](https://user-images.githubusercontent.com/56411572/66601050-59b53d00-eb7d-11e9-8ebf-3c54d376a60a.png)

Utilizando a PrestaShop 1.7, acesse no Back Office a tab "Pagamento > Preferências > Restrições de transportadora" e verifique se as transportadoras estão vinculadas à forma de pagamento.
Por favor, veja este issue: https://github.com/pagseguro/prestashop/issues/60

> E apos preencher o boleto e clicar em finalizar:
> ![image](https://user-images.githubusercontent.com/56411572/66601084-6e91d080-eb7d-11e9-871e-2db95e19dd38.png)
> Todos os logs estão assim:
> ![image](https://user-images.githubusercontent.com/56411572/66601125-849f9100-eb7d-11e9-9dec-b93bdfd2d2cb.png)

No seu payload o campo shippingAddressState está como "null". E este é um campo obrigatório...
Por favor, veja este issue: https://github.com/pagseguro/prestashop/issues/58

Qualquer dúvida ficamos à disposição.

Atenciosamente,
Equipe PrestaBR

**Comment by alfonsoalexandre** [comment]
Adicionei o State:name no formulario, está enviando o shippingAddressState, mas continua dando o mesmo erro.. segue log:
![image](https://user-images.githubusercontent.com/56411572/66629195-6f575080-ebd7-11e9-85fd-a111ed46bcbe.png)
No tocante ao erro 0, a transportadora já esta vinculada ao meio de pagamento, no entanto nao existe a opção boleto lá.
Detalhe, esse erro 0 só aparece quando a loja em modo sandbox.

**Comment by prestabr** [comment]
Bom Dia alfonsoalexandre,

> Adicionei o State:name no formulario, está enviando o shippingAddressState, mas continua dando o mesmo erro.. segue log:
> ![image](https://user-images.githubusercontent.com/56411572/66629195-6f575080-ebd7-11e9-85fd-a111ed46bcbe.png)

Neste novo print está faltando o shippingAddressDistrict (Bairro) que é referenciado pelo campo address2. Compara com o print anterior... O único campo que mantemos como opcional é o shippingAddressComplement (se estiver em branco ele recebe o parâmetro false).

> No tocante ao erro 0, a transportadora já esta vinculada ao meio de pagamento, no entanto nao existe a opção boleto lá.

Ótimo sobre as transportadoras. Antes de realizar novos testes confere se os dados do cadastro do cliente estão 100%.

> Detalhe, esse erro 0 só aparece quando a loja em modo sandbox.

O sandbox tem o token diferente do de produção, conferiu este detalhe? Se o debug da loja estiver ativo também pode pode causar problemas. A API sandbox passa por contantes testes e ajustes, recomendamos que realize os testes finais em sua loja utilizando o ambiente de produção para evitar qualquer divergência.

Por favor, posta aqui pra gente se você conseguiu processar o pedido via Boleto.

Atenciosamente,
Equipe PrestaBR
