### ISSUE TITLE
Botão para confirmar pagamento não habilita novamente.

### ISSUE THREAD

**Issue by zagalux** [pagseguro/prestashop#63]
Quando vou finalizar um pedido com cartão de crédito e algum dado está errado, ele aparece os erros e pede para colocar a informalção correta, assim desabilitando o botão para concluir o pedido novamente até que entre com os dados, porém ele sempre requer que os dados do numero de cartão e número de parcelas sejam colocados novamente, mesmo estando lá para liberar o botão. 
 Não é intuitivo e causa confusão para o usuário.

 Versão PS - 1.7.6.0 - Checkout transparente
 PHP - 7.2.23

**Comment by prestabr** [comment]
Bom Dia zagalux,

Obrigado pelo seu feedback!

Apenas para contextualizar...

Sempre que o cliente acessar a tela de checkout o módulo, em tempo real via JavaScript, se comunica com a API para iniciar uma sessão de pagamento. Habilitando a opção "Exibir parâmetros no Console do navegador?", você conseguirá visualizar os parâmetros de sessão chamados de "Session ID" e "Sender Hash". https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Quando o cliente informa o número do cartão e os dados estão incorretos o módulo exibe o alerta na tela, reinicia a sessão de pagamento e força o cliente a conferir os dados novamente, incluindo o parcelamento que está diretamente relacionado à bandeira, e outros detalhes técnicos como o "Token do Cartão de Crédito" (não visível/disponível por motivos de segurança).

No processo de pagamento primeiramente o cliente preenche o número do cartão de crédito, na sequência ele preenche a data de validade e depois o cvv. Por fim é que ele parte para a escolha do parcelamento. Escolher o parcelamento antes de preencher os dados do cartão de crédito não é a ordem comum do processo de compra e preenchimento dos dados.

Seguindo a ordem correta de preenchimento, mesmo que o cliente erre o número do cartão o reinicio da dessão se torna imperceptível, garantindo a segurança no processo de compra, sem impactar negativamente na navegação do cliente.

Atenciosamente,
Equipe PrestaBR

**Comment by zagalux** [comment]
O problema é que se os dados do cartão estão corretos e um dado do endereço, por exemplo numero da casa faltando, está errado ele faz com que o cliente tenha que obrigatóriamente clique novamente no numero do cartão para habilitar o botão de pagar.

**Comment by prestabr** [comment]
Bom dia zagalux,

O botão "Confirmar endereço do titular" não executa nenhum tipo de validação em tempo real, também não utiliza JavaScript.

Depois que o cliente informar os dados e clicar em pagar, se houver algum dado incompleto, então é inevitável que ele preencha novamete as parcelas ou dados do cartão e revise o que estiver faltando.

Confere que a interferência no botão de pagar é originada pelos "Termos de Serviço" (Parâmetros da Loja > Configurações de pedidos > Termos de Serviço), que é uma configuração opcinal da PrestaShop e que geralmente é substituida por alguma informação estática na área de CMS, a fim de simplificar o processo de compra para o cliente.

Agradecemos o seu feedback, vamos avaliar a relevância desta questão para incluir na próxima update que será realizada em +- 1 semana.

Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR

**Comment by glaucomodera** [comment]
Amigos, vocês não estão entendendo a questão do colega...  O problema que eu também estou sofrendo é o seguinte: se o cliente digita algum dado errado, mesmo consertando o referido dado e TUDO completamente preenchido, inclusive a quantidade de parcelas, o botão CONFIRMAR não fica habilitado. Para habilitar o botão o cliente tem que apagar e digitar os dados novamente ou clicar em cima do número do cartão digitado para dar um bug e o botão CONFIRMAR ficar habilitado.
