### ISSUE TITLE
Checkout Transparente - undefined index

### ISSUE THREAD

**Issue by WebGF** [pagseguro/prestashop#64]
Estou com problemas no modulo Pagseguro Checkout Transparente na versão 1.6x

Ele esta todo configurado e chega até a gerar a compra la no pagseguro, mas ao finalizar a compra no site aparece uma serie de erros na tela.

*Obs.: A loja esta na versão 1.6.1.1 do prestashop e o modulo na versão v1.1.6

Ao efetuar o pagamento por cartão de credito ou boleto aparece a seguinte tela:

![alertas_pos_compra_boleto](https://user-images.githubusercontent.com/56832697/67210827-1c0faa00-f3f0-11e9-9617-2b0d752e9b63.jpg)

Na pagina de configuração do modulo também aparece o seguinte alerta:

![alerta_config_modulo](https://user-images.githubusercontent.com/56832697/67210863-2f227a00-f3f0-11e9-855c-50503374a4eb.jpg)

**Comment by WebGF** [comment]
Aparentemente o problema foi resolvido desativando o modo Debug

/* Debug only */

if (!defined('_PS_MODE_DEV_')) {

define('_PS_MODE_DEV_', **false**);

}

**Comment by prestabr** [comment]
Bom Dia WebGF,

O módulo em modo de produção com a loja em modo debug acaba gerando problemas. O debug pode limitar a coleta de dados e redirecionamentos. Basicamente o boleto executa um redirect no validation pra processar o insert e posterior tela de confirmação de pedido.

Por favor, confere este issue (mesma questão): https://github.com/pagseguro/prestashop/issues/53

Atenciosamente,
Equipe PrestaBR
