### ISSUE TITLE
Problemas no parcelamento

### ISSUE THREAD

**Issue by WebGF** [pagseguro/prestashop#66]
Olá,

O modulo esta apresentando um problema quando o cliente tenta efetuar uma compra parcelada.

Se o pagamento for efetuado em 1x a venda é efetuada normalmente.

Se o cliente tenta efetuar a compra em 2x ou mais, o site retorna "forma de pagamento temporariamente indisponível"

*PagSeguro - Checkout Transparente v.1.1.6 (Versão instalada)

Qual a solução para este problema?

**Comment by prestabr** [comment]
Boa Tarde WebGF,

Dificuldades com o parcelamento são originadas pelo "GetInstallments", a última correção foi na versão 1.1.3 (https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#changelog).

Se você atualizou o módulo, confere se todos os arquivos foram substituídos corretamente e se as permissões dos diretórios e arquivos estão corretas em sua hospedagem (755 para pastas e 644 para arquivos). Também limpe o cache da loja no menu "Parâmetros Avançados > Desempenho".

Na sequência confere se o parcelamento está cadastrado nas configurações do módulo e na sua conta no PagSeguro (https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#4---parcelamento).

Depois de conferir estes detalhes tente fazer novos testes e se mesmo assim houver dificuldades, acessa no menu "Compras ou Pedidos > PagSeguro - Logs". Na área de Logs você conseguirá analisar o que foi enviado e recebido na comunicação com a sua loja e o PagSeguro (https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#7---registro-de-transa%C3%A7%C3%B5es--gerenciamento-de-logs). 

Utilize os filtros para facilitar (ID Cart, Method e URL):

![67250510-0fb43d00-f442-11e9-9ac6-277db341d295](https://user-images.githubusercontent.com/7054224/67965499-e5e8dc00-fbe0-11e9-9a90-cdd0f4e88ac9.png)

Por favor, posta aqui pra gente o Log ou se já está funcionando normalmente.

Atenciosamente,
Equipe PrestaBR

**Comment by WebGF** [comment]
Realizei todos os procedimentos conforme a orientação e o problema ainda persiste.

Segue o link da loja caso queiram fazem algum teste diretamente: https://www.ciencor.com.br/

Segue o log de uma compra que não apresentou a mensagem de erro.

*Obs.: Eu ocultei algumas informações que eu julgo serem sensíveis.
![log_pagseguro](https://user-images.githubusercontent.com/56832697/68054640-80264e00-fccd-11e9-9dff-e4a60f507df0.jpg)

**Comment by prestabr** [comment]
Boa Tarde WebGF,

Fizemos um cadastro em sua loja com o email sac@prestabr.com.br, realizamos um pedido via boleto e outro via cartão e ambos foram ok.

> Realizei todos os procedimentos conforme a orientação e o problema ainda persiste.
> 
> Segue o link da loja caso queiram fazem algum teste diretamente: https://www.ciencor.com.br/
> 
> Segue o log de uma compra que apresentou a mensagem de erro.
> 
> *Obs.: Eu ocultei algumas informações que eu julgo serem sensíveis.
> ![log_pagseguro](https://user-images.githubusercontent.com/56832697/68054640-80264e00-fccd-11e9-9dff-e4a60f507df0.jpg)

Neste print os campos "installmentQuantity" e "installmentValue" estão ok. Tendo essas informações no payload significa que tudo ocorreu como esperado na tela de checkout. 

Por este print não é possível determinar a causa do problema. Na área de Logs filtra pelo ID do Carrinho, 4969, e tenta localizar a Resposta da API.

Se preferir, por favor, encaminha pra gente os dados de acesso ao backoffice da sua loja que a gente analisa os Logs e identifica o problema pra você.

E-mail: sac@prestabr.com.br

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Boa Noite WebGF,

Apenas um feedback para documentarmos a solução...

Fizemos alguns testes em sua loja e identificamos que está ausente o parâmetro "noInterestInstallmentQuantity" no payload da transação.

Esta informação é definida nas configurações de parcelamento do módulo. Nas versões mais recentes alteramos os campos "Quantidade máxima de parcelas" e "Quantidade de parcelas sem juros" de "input" para "select", porque muitas pessoas preenchiam a quantidade de parcelas errado.

Solução: Por favor, acesse as configurações do módulo, selecione as opções e clique em Salvar. Se já estiver selecionado basta clicar em Salvar.

Qualquer problema ficamos à disposição.

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Boa Tarde WebGF,

Estamos com outras demandas exatamente igual a sua, fizemos mais testes, verificamos geral e tendo as parcelas corretamente salvas no banco de dados, o problema passar a girar em torno da quantidade de parcelas sem júros configurada no módulo.

Sua configuração:

Quantidade máxima de parcelas: 12x
Quantidade de parcelas sem juros: 1x

A quantidade de parcelas sem juros precisa ser a partir de 2x, isso porque 1x é sempre sem juros.

Acabamos de atualizar o módulo no GitHub para a PrestaShop 1.6.x e 1.7.x.

Atenciosamente,
Equipe PrestaBR

**Comment by mobbil** [comment]
Equipe,

fiz a instalaçao desse modulo no 1.7 no entanto a parcela não funciona quando clico para selecionar a quantidade dos juros fica travado no "--" e não tem como marcar, pode verificar qual o problema?

**Comment by prestabr** [comment]
Olá mobbil,

Confere essa dica: https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Segue o passo-a-passo do Debug na documentação, se houver algum conflito de JavaScript no Console posta aqui pra gente visualizar e tentar te ajudar.

Atenciosamente,
Equipe PrestaBR

**Comment by mobbil** [comment]
veja ai o token está certo e a sessao parece que é outro problema

![conflito](https://user-images.githubusercontent.com/15359829/82710830-3ba6d380-9c5a-11ea-9ace-c79a40419179.jpg)

**Comment by prestabr** [comment]
Olá mobbil,

Confere por favor, este issue trata sobre o erro no seu Console: 
https://github.com/pagseguro/prestashop/issues/91

Dica para solução:
https://github.com/pagseguro/prestashop/issues/91#issuecomment-627532061

Atenciosamente,
Equipe PrestaBR
