### ISSUE TITLE
Testando em modo sandbox... não tá pegando o estado (uf)

### ISSUE THREAD

**Issue by giovannefc** [pagseguro/prestashop#67]
Olá. Estou testando o módulo em sandbox aqui, estou recebendo o retorno:

array:3 [▼
  0 => "A conexão com o Pagseguro retornou com erro: 0 -  (HTTP: 400)"
  1 => "Erro no processamento do cartão."
  2 => array:2 [▼
    "codigo" => 53033
    "descricao" => "estado do endereço de entrega é necessário. (.shipping address state is required.)"
  ]
]

Mesmo estando devidamente preenchido.... tanto no cartão, quanto boleto ...

**Comment by prestabr** [comment]
Boa Noite giovannefc,

Obrigado por utilizar o módulo oficial! :)

A API sandbox passa por contantes testes e ajustes, recomendamos que realize os testes finais em sua loja utilizando o ambiente de produção para evitar qualquer divergência.

Ainda ontem houve um deploy do sandbox, é possível que outros problemas intermitentes venham a ocorrer.

Atenciosamente,
Equipe PrestaBR

**Comment by giovannefc** [comment]
Mas no log ele está enviando o parâmetro de UF como null.

Não são testes finais. Eu acabei de instalar o módulo e estou tentando finalizar uma venda pra testar o funcionamento... Como vou testar a loja em produção? Não tem sentido. Sem querer ser chato, mas o sandbox foi feito pra isso mesmo ...

**Comment by prestabr** [comment]
Bom Dia giovannefc,

Se você conseguiu analisar os Logs corretamente e tem a certeza que o campo UF está como null isso significa que falta configurar os estados em sua loja. Antes de realizar novos testes confere se os dados do cadastro do cliente estão 100%.

Habilitando os estados no país: https://github.com/pagseguro/prestashop/issues/58#issuecomment-545026313

O único campo que mantemos como opcional é o shippingAddressComplement (se estiver em branco ele recebe o parâmetro false).

Atenciosamente,
Equipe PrestaBR
