### ISSUE TITLE
Trazer dados do cartão de crédito cadastrados no pagseguro

### ISSUE THREAD

**Issue by WebGF** [pagseguro/prestashop#68]
Na verdade é uma duvida e não o problema.

Não sei exatamente onde publicar essa minha duvida, então coloquei aqui mesmo. (Desculpe se coloquei na área errada)

Minha duvida é se é possível o modulo puxar os dados do cartão de credito para os clientes que já possuem uma conta no pagseguro e ja tem um cartão cadastrado dentro do pagseguro.

O intuito é dar agilidade para o cliente finalizar a compra, sem ter que digitar todos os dados em todas as compras.

O modulo tem essa capacidade?

Se sim, como isso acontece?

**Comment by prestabr** [comment]
Boa Tarde WebGF,

Sem problemas, sempre que precisar entrar em contato pode postar por aqui mesmo :).

O módulo não faz o procedimento de salvar ou puxar os dados de cartão de crédito do cliente. Este procedimento vai contra-mão das políticas de segurança e padrão PCI DSS estabelecido no módulo.

Atenciosamente,
Equipe PrestaBR
