### ISSUE TITLE
Pagamento Temporariamente Indisponível no Momento...... V2

### ISSUE THREAD

**Issue by glaucomodera** [pagseguro/prestashop#69]
Olá amigos,

Primeiramente obrigado pela presteza. 

Eu abri esse post inicialmente e ele já foi fechado (Pagamento Temporariamente Indisponível no Momento......#65). Eu continuo com o problema e vocês pediram para eu liberar acesso ao meu painel prestashop e FTP. Eu fiz isto e mandei e-mail para vocês (sac@prestabr.com.br) , porém até agora não obtive um retorno de recebimento ou de análise. 

Como devo proceder ?

**Comment by prestabr** [comment]
Boa Tarde glaucomodera,

Recebemos a sua solicitação por e-mail, ontem à noite às 22:37hs, obrigado pelos detalhes.

Em até 72hs úteis retornaremos o seu contato através do e-mail sac@prestabr.com.br.

Atenciosamente,
Equipe PrestaBR

**Comment by glaucomodera** [comment]
Obrigado.

**Comment by glaucomodera** [comment]
eu vi que vocês subiram a versão 1.1.7 mas estou aguardando para saber sobre esse problema antes de atualizar, pois na versão 1.1.5 funcionava normalmente.

**Comment by prestabr** [comment]
Olá glaucomodera,

A versão do módulo indifere, o Core do módulo é o mesmo na 1.1.5 e 1.1.6 e 1.1.7.

Ainda não analisamos o seu caso, mas outras lojas também enfrentaram dificuldades e a questão não está relacionada à loja virtual ou ao módulo de integração. A API apresentou instabilidade intermitente que ocasionou a falha no processamento da transação. A equipe técnica do PagSeguro já está trabalhando para estabilizar os serviços.

Pode atualizar o módulo tranquilamente, só certifique-se de limpar o cache da loja.

Atenciosamente,
Equipe PrestaBR

**Comment by glaucomodera** [comment]
Tks....

**Comment by prestabr** [comment]
Boa Noite Glauco,

Apenas para organizar, postamos o feedback neste issue: https://github.com/pagseguro/prestashop/issues/65#issuecomment-549620958

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Boa Tarde Glauco,

Estamos com outras demandas exatamente igual a sua, fizemos mais testes, verificamos geral e tendo as parcelas corretamente salvas no banco de dados, o problema passar a girar em torno da quantidade de parcelas sem júros configurada no módulo.

Sua configuração:

Quantidade máxima de parcelas: 12x
Quantidade de parcelas sem juros: 1x

A quantidade de parcelas sem juros precisa ser a partir de 2x, isso porque 1x é sempre sem juros.

Acabamos de atualizar o módulo no GitHub para a PrestaShop 1.6.x e 1.7.x.

Atenciosamente,
Equipe PrestaBR
