### ISSUE TITLE
Pagamento Temporariamente Indisponível no Momento...... V3 + Error 500

### ISSUE THREAD

**Issue by glaucomodera** [pagseguro/prestashop#70]
Olá pessoal, 

Obrigado por sempre responder meus questionamentos. 

Vocês pediram acesso ao meu FTP + Painel do PretaShop e fizeram todos os ajustes necessários conforme #66 e #65. Inclusive atualizaram meu módulo para 1.1.7

Acontece que um cliente tentou comprar em meu site agora parcelado em 3x e deu "Pagamento Temporariamente Indisponível no Momento..." Em seguida tentou parcelar em 4x e deu o mesmo erro - "Pagamento Temporariamente Indisponível no Momento..."

Eu orientei o cliente a pagar em 1x e quando tentou novamente a compra foi aprovada somente no PagSeguro, porque não gerou pedido em meu site.  Para o cliente deu Erro Server 500. 

Por favor, amigos, preciso de muita ajuda de vocês.

**Comment by glaucomodera** [comment]
O acesso ao meu FTP e Painel continuam os mesmos.

**Comment by glaucomodera** [comment]
(75) DATA: 05/11/2019 12:44:33 - TIPO: VALIDATION - MÉTODO: PROCESSA CARTAO

 "appId": "prestashop-16-30d",
    "appKey": "(removido)",
    "authorizationCode": "(removido)",
    "paymentMethod": "creditCard",
    "notificationURL": "https://modera.com.br/modules/pagseguropro/notification.php",
    "currency": "BRL",
    "paymentMode": "default",
    "reference": "9328.95296477",
    "itemId1": "105",
    "itemDescription1": "Luvas Helanca 3/4",
    "itemAmount1": "20.00",
    "itemQuantity1": "1",
    "itemId2": "184",
    "itemDescription2": "Faixa de Cabelo Turbante Bolinhas",
    "itemAmount2": "14.00",
    "itemQuantity2": "1",
    "itemId3": "95",
    "itemDescription3": "Saiote Anu00e1gua C/ Elu00e1stico Vestido Anos 60",
    "itemAmount3": "44.00",
    "itemQuantity3": "1",
    "itemId4": "234",
    "itemDescription4": "Vestido De Bolinha Branco P40",
    "itemAmount4": "165.00",
    "itemQuantity4": "1",
    "itemId5": "179",
    "itemDescription5": "Tiara Arco De Cabelo Bolinha Retru00f4 Anos 60",
    "itemAmount5": "15.00",
    "itemQuantity5": "1",
    "itemId6": "210",
    "itemDescription6": "u00d3culos Gatinho Retro Triu00e2ngulo",
    "itemAmount6": "25.00",
    "itemQuantity6": "1",
    "itemId7": "210",
    "itemDescription7": "u00d3culos Gatinho Retro Triu00e2ngulo",
    "itemAmount7": "25.00",
    "itemQuantity7": "1",
    "itemId8": "180",
    "itemDescription8": "Colar de Bolas Gargantilha Vintage Retro Anos 60",
    "itemAmount8": "18.00",
    "itemQuantity8": "1",
    "itemId9": "145",
    "itemDescription9": "u00d3culos Gatinho Retro Anos 60",
    "itemAmount9": "30.00",
    "itemQuantity9": "1",
    "senderEmail": "claudia0408_75@hotmail.com",
    "senderName": "claudia maria de paula",
    "senderCPF": "01078596611",
    "senderAreaCode": "31",
    "senderPhone": "997445152",
    "senderHash": "029a78dfccb1f69bcaa0c003ab9ebc96cb5154e2ab779fd1a41e50f921486000",
    "shippingType": "3",
    "shippingCost": "26.20",
    "shippingAddressCountry": "BRA",
    "shippingAddressState": "MG",
    "shippingAddressCity": "Belo Horizonte",
    "shippingAddressPostalCode": "30270450",
    "shippingAddressDistrict": "Parau00edso",
    "shippingAddressStreet": "Rua Isaura Possidu00f4nio",
    "shippingAddressNumber": "24",
    "shippingAddressComplement": false,
    "creditCardToken": "97eb73a355334f969a37b52457673145",
    "installmentQuantity": "3",
    "installmentValue": "133.15",
    "creditCardHolderName": "claudia maria de paula almeida",
    "creditCardHolderBirthDate": "04/08/1975",
    "creditCardHolderCPF": "(REMOVIDO)",
    "creditCardHolderAreaCode": "31",
    "creditCardHolderPhone": "(REMOVIDO)",
    "billingAddressPostalCode": "30270450",
    "billingAddressStreet": "Rua Isaura Possidu00f4nio",
    "billingAddressNumber": "24",
    "billingAddressComplement": false,
    "billingAddressDistrict": "Parau00edso",
    "billingAddressCity": "Belo Horizonte",
    "billingAddressState": "MG",
    "billingAddressCountry": "BRA"

**Comment by glaucomodera** [comment]
(79) DATA: 05/11/2019 12:45:52 - TIPO: VALIDATION - MÉTODO: PROCESSA CARTAO

 "appId": "prestashop-16-30d",
    "appKey": "(REMOVIDO)",
    "authorizationCode": "(REMOVIDO)",
    "paymentMethod": "creditCard",
    "notificationURL": "https://modera.com.br/modules/pagseguropro/notification.php",
    "currency": "BRL",
    "paymentMode": "default",
    "reference": "9328.04834872",
    "itemId1": "105",
    "itemDescription1": "Luvas Helanca 3/4",
    "itemAmount1": "20.00",
    "itemQuantity1": "1",
    "itemId2": "184",
    "itemDescription2": "Faixa de Cabelo Turbante Bolinhas",
    "itemAmount2": "14.00",
    "itemQuantity2": "1",
    "itemId3": "95",
    "itemDescription3": "Saiote Anu00e1gua C/ Elu00e1stico Vestido Anos 60",
    "itemAmount3": "44.00",
    "itemQuantity3": "1",
    "itemId4": "234",
    "itemDescription4": "Vestido De Bolinha Branco P40",
    "itemAmount4": "165.00",
    "itemQuantity4": "1",
    "itemId5": "179",
    "itemDescription5": "Tiara Arco De Cabelo Bolinha Retru00f4 Anos 60",
    "itemAmount5": "15.00",
    "itemQuantity5": "1",
    "itemId6": "210",
    "itemDescription6": "u00d3culos Gatinho Retro Triu00e2ngulo",
    "itemAmount6": "25.00",
    "itemQuantity6": "1",
    "itemId7": "210",
    "itemDescription7": "u00d3culos Gatinho Retro Triu00e2ngulo",
    "itemAmount7": "25.00",
    "itemQuantity7": "1",
    "itemId8": "180",
    "itemDescription8": "Colar de Bolas Gargantilha Vintage Retro Anos 60",
    "itemAmount8": "18.00",
    "itemQuantity8": "1",
    "itemId9": "145",
    "itemDescription9": "u00d3culos Gatinho Retro Anos 60",
    "itemAmount9": "30.00",
    "itemQuantity9": "1",
    "senderEmail": "claudia0408_75@hotmail.com",
    "senderName": "claudia maria de paula",
    "senderCPF": "01078596611",
    "senderAreaCode": "31",
    "senderPhone": "997445152",
    "senderHash": "5654491b2f1b8d6d0f3e9a16f35a8eb1e30c908268a85087a733111c61b77d99",
    "shippingType": "3",
    "shippingCost": "26.20",
    "shippingAddressCountry": "BRA",
    "shippingAddressState": "MG",
    "shippingAddressCity": "Belo Horizonte",
    "shippingAddressPostalCode": "30270450",
    "shippingAddressDistrict": "Parau00edso",
    "shippingAddressStreet": "Rua Isaura Possidu00f4nio",
    "shippingAddressNumber": "24",
    "shippingAddressComplement": false,
    "creditCardToken": "757ddd55194a4277a4a281cbb870f40d",
    "installmentQuantity": "4",
    "installmentValue": "101.32",
    "creditCardHolderName": "claudia maria de paula",
    "creditCardHolderBirthDate": "04/08/1975",
    "creditCardHolderCPF": "(REMOVIDO)",
    "creditCardHolderAreaCode": "31",
    "creditCardHolderPhone": "(REMOVIDO)",
    "billingAddressPostalCode": "30270450",
    "billingAddressStreet": "Rua Isaura Possidu00f4nio",
    "billingAddressNumber": "24",
    "billingAddressComplement": false,
    "billingAddressDistrict": "Parau00edso",
    "billingAddressCity": "Belo Horizonte",
    "billingAddressState": "MG",
    "billingAddressCountry": "BRA"

**Comment by glaucomodera** [comment]
(81) DATA: 05/11/2019 12:47:56 - TIPO: CURL - MÉTODO: POST
(COMPRA APROVADA - SOMENTE NO PAGSEGURO, POIS DEU ERRO SERVER 500)

 "appId": "prestashop-16-30d",
    "appKey": "(REMOVIDO)",
    "authorizationCode": "(REMOVIDO)",
    "paymentMethod": "creditCard",
    "notificationURL": "https://modera.com.br/modules/pagseguropro/notification.php",
    "currency": "BRL",
    "paymentMode": "default",
    "reference": "9328.38653514",
    "itemId1": "105",
    "itemDescription1": "Luvas Helanca 3/4",
    "itemAmount1": "20.00",
    "itemQuantity1": "1",
    "itemId2": "184",
    "itemDescription2": "Faixa de Cabelo Turbante Bolinhas",
    "itemAmount2": "14.00",
    "itemQuantity2": "1",
    "itemId3": "95",
    "itemDescription3": "Saiote Anu00e1gua C/ Elu00e1stico Vestido Anos 60",
    "itemAmount3": "44.00",
    "itemQuantity3": "1",
    "itemId4": "234",
    "itemDescription4": "Vestido De Bolinha Branco P40",
    "itemAmount4": "165.00",
    "itemQuantity4": "1",
    "itemId5": "179",
    "itemDescription5": "Tiara Arco De Cabelo Bolinha Retru00f4 Anos 60",
    "itemAmount5": "15.00",
    "itemQuantity5": "1",
    "itemId6": "210",
    "itemDescription6": "u00d3culos Gatinho Retro Triu00e2ngulo",
    "itemAmount6": "25.00",
    "itemQuantity6": "1",
    "itemId7": "210",
    "itemDescription7": "u00d3culos Gatinho Retro Triu00e2ngulo",
    "itemAmount7": "25.00",
    "itemQuantity7": "1",
    "itemId8": "180",
    "itemDescription8": "Colar de Bolas Gargantilha Vintage Retro Anos 60",
    "itemAmount8": "18.00",
    "itemQuantity8": "1",
    "itemId9": "145",
    "itemDescription9": "u00d3culos Gatinho Retro Anos 60",
    "itemAmount9": "30.00",
    "itemQuantity9": "1",
    "senderEmail": "claudia0408_75@hotmail.com",
    "senderName": "claudia maria de paula",
    "senderCPF": "01078596611",
    "senderAreaCode": "31",
    "senderPhone": "997445152",
    "senderHash": "696bc9acd1961213c21110791035dc5d66095faa0b3433e35a9f3c558524cb3b",
    "shippingType": "3",
    "shippingCost": "26.20",
    "shippingAddressCountry": "BRA",
    "shippingAddressState": "MG",
    "shippingAddressCity": "Belo Horizonte",
    "shippingAddressPostalCode": "30270450",
    "shippingAddressDistrict": "Parau00edso",
    "shippingAddressStreet": "Rua Isaura Possidu00f4nio",
    "shippingAddressNumber": "24",
    "shippingAddressComplement": false,
    "creditCardToken": "13dd2c531ced48d9a867754e2a58ed76",
    "installmentQuantity": "1",
    "installmentValue": "382.20",
    "creditCardHolderName": "claudia maria de paula",
    "creditCardHolderBirthDate": "04/08/1975",
    "creditCardHolderCPF": "(REMOVIDO)",
    "creditCardHolderAreaCode": "31",
    "creditCardHolderPhone": "(REMOVIDO)",
    "billingAddressPostalCode": "30270450",
    "billingAddressStreet": "Rua Isaura Possidu00f4nio",
    "billingAddressNumber": "24",
    "billingAddressComplement": false,
    "billingAddressDistrict": "Parau00edso",
    "billingAddressCity": "Belo Horizonte",
    "billingAddressState": "MG",
    "billingAddressCountry": "BRA"

**Comment by glaucomodera** [comment]
![APROVADO](https://user-images.githubusercontent.com/56834125/68224922-4a83ac80-ffce-11e9-801f-1cd44d637171.JPG)

**Comment by prestabr** [comment]
Boa Tarde Glauco,

Estamos com outras demandas exatamente igual a sua, fizemos mais testes, verificamos geral e tendo as parcelas corretamente salvas no banco de dados, o problema passar a girar em torno da quantidade de parcelas sem júros configurada no módulo.

Sua configuração:

Quantidade máxima de parcelas: 12x
Quantidade de parcelas sem juros: 1x

A quantidade de parcelas sem juros precisa ser a partir de 2x, isso porque 1x é sempre sem juros.

Acabamos de atualizar o módulo aqui no GitHub para a PrestaShop 1.6.x e 1.7.x. Também já atualizamos em sua loja.

Atenciosamente,
Equipe PrestaBR
