### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by glaucomodera** [pagseguro/prestashop#71]
Olá, 

Amigos, entendo que vocês estão resolvendo o problema do parcelamento. 

Acontece que quando a compra é aprovada está dando 500 Server Error.

**Comment by glaucomodera** [comment]
![error](https://user-images.githubusercontent.com/56834125/68226235-799b1d80-ffd0-11e9-95a4-259e51eba437.JPG)

**Comment by prestabr** [comment]
Boa Tarde glaucomodera,

Aí, infelizmente, já não é um problema do módulo...

Tenta desativar as outras opções de pagamento, limpa o cache da sua loja, certifique-se que não exista conflitos de php, smarty, etc, na sua tela de confirmação de pedido. Recomendamos que procure o auxílio de um profissional.

Caso queira testar o módulo em outro ambiente:

Loja: https://prestabr.com.br/pagseguro16/
E-mail: sac@prestabr.com.br
Senha: teste123*

Atenciosamente,
Equipe PrestaBR
