### ISSUE TITLE
Pagamento Cartão + Data de Nascimento + Smartphone

### ISSUE THREAD

**Issue by glaucomodera** [pagseguro/prestashop#72]
Olá amigos, 
Parabéns pelo trabalho de vocês. Como já é sabido por todos aqui. Dentro em breve teremos a versão 1.1.9 com as correções de parcelamento. 

Se possível, deixar o pagamento via Smartphone mais responsivo. Por exemplo: quando o usuário tenta efetuar uma compra utilizando o cartão de terceiros, ele precisa atualizar os dados do pagamento do titular, inclusive a data de nascimento. Acontece que a data de nascimento aparece em formato de calendário e para os clientes leigos, fica difícil de saber que precisa selecionar o ano lá em cima (no canto superior esquerdo) e depois escolher o ano na vertical, em seguida, precisa selecionar o mês usando as setas na horizontal, para por fim, selecionar o dia no calendário. 

Veja o exemplo: 
![WhatsApp Image 2019-11-05 at 7 28 16 PM](https://user-images.githubusercontent.com/56834125/68251816-ac5e0980-0002-11ea-83c1-4013dce6a523.jpeg)

Se possível, tornar a mudança desse campo mais acessível. Minha loja é voltada para pessoas da terceira idade e meus clientes têm dificuldade para alterar a data de nascimento do titular do cartão e reclamam. 

Abraços pessoal

**Comment by prestabr** [comment]
Boa Noite glaucomodera,

Agradecemos seu feedback! :)

Atenciosamente,
Equipe PrestaBR
