### ISSUE TITLE
Problema no Parcelamento - Parcelamento configurado para 1x s/ juros

### ISSUE THREAD

**Issue by arodel** [pagseguro/prestashop#73]
Olá,

Tenho problemas no parcelamento a muito tempo, havia até desistido de usar o pagseguro em meu site e estava usando outro porta.. Vi agora que vocês fizeram boa evolução, mas ainda existe um problema.

Vocês disseram que "A quantidade de parcelas sem juros precisa ser a partir de 2x, isso porque 1x é sempre sem juros", e na nova versão nem existe mais a possibilidade de escolher "1x ".

O problema é que não quero oferecer 2x sem juros, e agora sou obrigado a oferecer 2x sem juros. Nossa compra parcelada deve ser COM JUROS já a partir de 2x. Como resolvemos isso? Gostaria muito de voltar a utilizar o PagSeguro em nosso e-commerce.

**Comment by glaucomodera** [comment]
Bom dia a todos, compartilho o mesmo sentimento do nosso amigo Arodel.

Abraços.

**Comment by prestabr** [comment]
Boa Tarde arodel,

Agradecemos o seu feedback!

Alteramos a quantidade de parcelas sem júros nas configurações do módulo por razões técnicas a fim de corrigir bugs e problemas gerais de funcionamento.

No módulo você configura a partir de 2x sem juros porque 1x é sempre sem juros. Este detalhe de funcionamento é uma regra da API de Checkout Transparente. Por razões técnicas não é possível oferecer apenas 1x sem júros.

Com esta última correção adaquemos 100% do funcionamento do módulo para trabalhar nesta API, problemas de funcionamento relacionados à parcelamento não existem mais.

Em breve teremos novidades sobre melhorias gerais na API de Checkout Transparente, novas soluções, atualizações do módulo, etc. Estaremos disponibilizando aqui no GitHub :)

Abraço.

Atenciosamente,
Equipe PrestaBR

**Comment by arodel** [comment]
Olá, agradeço muito a rápida resposta.
Porém, preciso discordar dessa solução, e peço que até finalizarem esse issue o mantenham aberto.

Você não pode dizer que o módulo está adequado 100% se ele obriga você a oferecer um parcelamento sem juros ao cliente, me desculpe mas isso não faz sentido algum... Não existe no módulo uma maneira de desabilitar o parcelamento e o módulo então OBRIGA A OFERECER PARCELAMENTO SEM JUROS AO CLIENTE, quem assume esse custo das 2x sem juros?

Por favor, revejam esse problema, isso é um ISSUE grave, tem de existir a possibilidade de 2x - 12x COM JUROS.

**Comment by prestabr** [comment]
Olá arodel,

Infelizmente não é um problema de funcionamento do módulo, não estamos tratando uma issue neste sentido. Entendemos o problema, concordamos com você, mas o módulo foi adequado de acordo com a regra de funcionamento da API de Checkout Transparente. 

Em em contato com depto técnico da API, todo o transtorno foi causado por instabilidades e falhas no serviço do getinstallments (mecanismo que processa o parcelamento na API).

Realizamos novos testes, verificamos juntos com o depto da API e voltamos a configuração original do módulo, que permitia o parcelamento sem juros em apenas 1x.

Para atualizar o módulo em sua loja, faz o download do módulo novamente (ainda na versão 1.1.8 na PS 1.6 e 1.0.3 na PS 1.7), subsituí todos os arquivos na pasta /modules/pagseguropro/ no seu FTP. Em seguida limpa o cache da loja na tab "Parâmetros Avançados > Desempenho" e acessa as configurações do módulo para selecionar e salvar 1x sem juros.

Atenciosamente,
Equipe PrestaBR

**Comment by arodel** [comment]
Olá prestabr,

Fiz as alterações e se eu escolho na configuração 1x sem juros, volta a dar o problema de não aceitar o pagamento parcelado. Se eu escolho 2x sem juros, o parcelamento funciona corretamente mas acabo sendo forçado a oferecer 2x sem juros para o cliente.

Isso não pode estar correto, tem de haver uma solução para que possamos oferecer parcelamento com juros para o cliente desde 2x, como o PagSeguro já oferece em outros meios de pagamento.

Por favor, voltem a contatar o pessoal da API para acharem uma solução...

Desde já agradeço a ajuda...

**Comment by prestabr** [comment]
Boa Tarde arodel,

O parcelamento em 1x está realmente funcionando. Na sua conta no PagSeguro você já verificou como estão as formas de pagamento aceitas e se tem alguma regra de parcelamento configurada?

Confere nosso ambiente de testes:

Loja: https://prestabr.com.br/pagseguro16/
E-mail: sac@prestabr.com.br
Senha: teste123*

Cartão fake p/ testes:

Número: 5555666677778884
Vencimento: 12/2022
CVV: 123

Atenciosamente,
Equipe PrestaBR

**Comment by arodel** [comment]
Olá

Acabei de fazer o teste em seu ambiente de testes e o problema persiste. A compra não foi finalizada e apareceu a mensagem _**"Forma de pagamento temporariamente indisponível. Por favor, tente novamente ou escolha outra forma de pagamento."**_.

O problema é que quando você deixa configurado nos parâmetros "quantidade de parcelas sem juros" em 1x. Na loja, o cliente consegue comprar em 1x corretamente, mas se ele na hora de pagar escolhe 2x, 3x, 4x... 12x então é que dá o erro e não efetua o pagamento. Faz o teste na loja de vocês, deixa configurado só 1x sem juros nos parâmetros internos e tenta fazer a compra escolhendo parcelar em 3x por exemplo... mesmo na loja de vocês vai dar problema.

Já, caso deixe configurado para 2x sem juros na configuração, então na hora de pagar o cliente pode escolher 3x, 4x até 12x mesmo com os juros que tudo funciona perfeito. Só que nesse caso, o problema é que para tudo funcionar acabamos sendo obrigados a dar a opção de 2x sem juros.

**Comment by prestabr** [comment]
Olá arodel,

Obrigado por realizar os testes e descrever o problema!

Vamos analisar, retornamos aqui em breve...

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Bom Dia arodel,

Novamente, muito obrigado por realizar os testes e descrever o problema detalhadamente.

Do nosso lado, realizamos novos testes, simulando todas as formas de parcelamento, junto com o pessoal da API e disponibilizamos uma nova atualização do módulo.

O problema está corrigido, para atualizar o módulo em sua loja é só seguir o passo-a-passo:

Para atualizar o módulo em sua loja, faz o download do módulo novamente (ainda na versão 1.1.8 na PS 1.6 e 1.0.3 na PS 1.7), subsituí todos os arquivos na pasta /modules/pagseguropro/ no seu FTP. Em seguida limpa o cache da loja na tab "Parâmetros Avançados > Desempenho" e acessa as configurações do módulo para selecionar e salvar 1x sem juros.

Após realizar novos testes do seu lado e atualizar o módulo em sua loja, por favor, posta aqui pra gente o resultado.

Qualquer dúvida ou problema ficamos à disposição.

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Bom Dia arodel,

Novamente, muito obrigado por realizar os testes e descrever o problema detalhadamente.

Do nosso lado, realizamos novos testes, simulando todas as formas de parcelamento, junto com o pessoal da API e disponibilizamos uma nova atualização do módulo.

O problema está corrigido, para atualizar o módulo em sua loja é só seguir o passo-a-passo:

Para atualizar o módulo em sua loja, faz o download do módulo novamente (ainda na versão 1.1.8 na PS 1.6 e 1.0.3 na PS 1.7), subsituí todos os arquivos na pasta /modules/pagseguropro/ no seu FTP. Em seguida limpa o cache da loja na tab "Parâmetros Avançados > Desempenho" e acessa as configurações do módulo para selecionar e salvar 1x sem juros.

Após realizar novos testes do seu lado e atualizar o módulo em sua loja, por favor, posta aqui pra gente o resultado.

Qualquer dúvida ou problema ficamos à disposição.

Atenciosamente,
Equipe PrestaBR

**Comment by arodel** [comment]
Bom dia Prestabr,

Atualizei o módulo e fiz novos testes, e está funcionando!
Parabéns e muito obrigado pelo comprometimento e rapidez.

Abs,
