### ISSUE TITLE
Erro no pagamento devido a segunda linha do endereço (problemas no cadastro do cliente, endereço sem numeral)

### ISSUE THREAD

**Issue by victordesouza** [pagseguro/prestashop#74]
Boa tarde, 
Foram relatadas falhas ao fazer pagamento com o pagseguro no site (sulinox.com.br), realizei testes e pra mim funcionava perfeitamente então fui mais a fundo em possíveis problemas.
E encontrei, no cadastro do endereço do cliente existem dois campos de endereço, o primário e o secundário, e voalá, quando o campo de segunda linha do endereço não é preenchido o pagamento falha apresentando um modal genérico, mas quando se preenche esse campo o pagamento acontece sem problemas.
Mas o endereço pode ser todo escrito na primeira linha, muitos clientes fazem isso e não preenchem os dois campos de endereço, entende?

Bom, gostaria de uma ajuda de como proceder com esse problema, como fazer as transações serem aceitas com apenas a primeira linha de endereço?

O site é sulinox.com.br, pode fazer um cadastro de testes para encontrar o problema.

Podem me ajudar?

**Comment by prestabr** [comment]
Boa Tarde victordesouza,


Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Boa Tarde victordesouza,

> Boa tarde,
> Foram relatadas falhas ao fazer pagamento com o pagseguro no site (sulinox.com.br), realizei testes e pra mim funcionava perfeitamente então fui mais a fundo em possíveis problemas.
> E encontrei, no cadastro do endereço do cliente existem dois campos de endereço, o primário e o secundário, e voalá, quando o campo de segunda linha do endereço não é preenchido o pagamento falha apresentando um modal genérico, mas quando se preenche esse campo o pagamento acontece sem problemas.
> Mas o endereço pode ser todo escrito na primeira linha, muitos clientes fazem isso e não preenchem os dois campos de endereço, entende?

Sim, é bem comum. O módulo de checkout transparente está preparado para trabalhar com diversos padrões de cadastro de numeral de endereço, mas ele não tem o controle sobre o cadastro do endereço na loja.

O correto é configurar em sua loja a obrigatoriedade do campo referente ao numeral do endereço, para que a partir daí o módulo possa caputrar essa informação para ser processada no pedido.

Você utiliza algum módulo para incluir o numeral na tela de cadastro de endereço? Sabe dizer o nome do campo? 

Você pode tentar torná-lo obrigatório acessando a tab "Clientes > Endereços" localizando no final da página "Definir os campos obrigatórios para esta seção".

> 
> Bom, gostaria de uma ajuda de como proceder com esse problema, como fazer as transações serem aceitas com apenas a primeira linha de endereço?
> 
> O site é sulinox.com.br, pode fazer um cadastro de testes para encontrar o problema.
> 
> Podem me ajudar?

Atenciosamente,
Equipe PrestaBR

**Comment by victordesouza** [comment]
> Você pode tentar torná-lo obrigatório acessando a tab "Clientes > Endereços" localizando no final da página "Definir os campos obrigatórios para esta seção".

Muito obrigado pelo retorno rápido, essa dica resolveu meu problema, agora os pagamentos estão ok.

Agradeço a atenção.

**Comment by prestabr** [comment]
Oi victordesouza,

Obrigado pelo feedback! Qualquer dúvida ou problema ficamos à disposição.

Atenciosamente,
Equipe PrestaBR
