### ISSUE TITLE
Erro ao tentar pagamento via cartão de crédito

### ISSUE THREAD

**Issue by rafaelsilvabra** [pagseguro/prestashop#75]
Amigos,

Estamos com pelo menos 8 casos de clientes que tentam pagar com cartão e aparece o erro anexado em tela. Olhando os LOGS não consegui ver algum erro claro. Com boleto funciona e tem venda que é feita com cartão normalmente.

Plugin usado esta com a última versao do 1.6.
Podem ajudar?

![compra_erro](https://user-images.githubusercontent.com/31866021/71092792-ac673280-2186-11ea-9d25-9b89efaef51c.jpeg)

**Comment by prestabr** [comment]
Bom Dia rafaelsilvabra,

Por favor, acessa a sua tab de Logs e filta o Method e URL, confere:

![Screenshot at 2019-12-18 11-19-13](https://user-images.githubusercontent.com/7054224/71093797-ad995f00-2188-11ea-9e68-0a8c4e0d5de4.png)

Se não houver um número de carrinho, tenta filtrar +- pela data/horário e localiza o POST que indica erro. A primeira linha, anterior ao erro, é o payload do pedido + retorno da api que indica o motivo do problema.

Exemplo:

![Screenshot at 2019-12-18 11-22-29](https://user-images.githubusercontent.com/7054224/71094291-7f684f00-2189-11ea-9a0d-5e52b6f3b7a5.png)

![7d0428fc-99a4-4058-9845-1e75377a072f](https://user-images.githubusercontent.com/7054224/71094375-a1fa6800-2189-11ea-9ce0-db071cb5dc6a.jpeg)

Neste exemplo, "sender is blocked", indica que o cliente tem alguma restrição na conta dele no PagSeguro e por este motivo não é possível processar o pagamento. Este bloqueio pode ser por fraude, saldo negativo, etc. Para resolver o cliente precisa entrar em contato com o PagSeguro para "acertar" as pendências na conta dele OU tentar comprar na loja com outro cpf/email de cadastro.

Atenciosamente,
Equipe PrestaBR

**Comment by rafaelsilvabra** [comment]
Muuuuuito orbrigado pelo retorno.

Então, seguindo o passos  de ontem para hoje tenho 11 erros.

**3 sobre isso**
![erro_1](https://user-images.githubusercontent.com/31866021/71103083-3f5c9880-2198-11ea-9cd5-0dee575b14ee.png)

**8 sobre isso**
![erro_2](https://user-images.githubusercontent.com/31866021/71103087-3f5c9880-2198-11ea-988a-9d8337a45a07.png)

**Comment by prestabr** [comment]
Olá rafaelsilvabra,

Pode contar com a gente...! ;)

> Muuuuuito orbrigado pelo retorno.
> 
> Então, seguindo o passos de ontem para hoje tenho 11 erros.
> 
> **3 sobre isso**
> ![erro_1](https://user-images.githubusercontent.com/31866021/71103083-3f5c9880-2198-11ea-9cd5-0dee575b14ee.png)
> 
Neste caso o CPF do cliente está ausente no cadastro dele na loja.

> **8 sobre isso**
> ![erro_2](https://user-images.githubusercontent.com/31866021/71103087-3f5c9880-2198-11ea-988a-9d8337a45a07.png)

É o bug que corrigimos nas versões mais recentes do módulo de Checkout Transparente, changelog: Fix GetInstallments/maxInstallmentNoInterest.

Para atualizar o módulo em sua loja, faz o download do módulo novamente (v.1.1.8 na PS 1.6 e 1.0.3 na PS 1.7), subsituí todos os arquivos na pasta /modules/pagseguropro/ no seu FTP. Em seguida limpa o cache da loja na tab "Parâmetros Avançados > Desempenho".

Atenciosamente,
Equipe PrestaBR

**Comment by rafaelsilvabra** [comment]
Eu coloquei mais uma informação sobre o CPF.
Já estou usando pra 1.6 a versão: v1.1.8

**Comment by prestabr** [comment]
Oi rafaelsilvabra,

Colocou mais uma informação? Consegue passar mais detalhes?

Sobre os 8 erros, se você já usa a v.1.1.8 e o problema persiste, por favor, posta aqui pra gente os Dados Enviados no seu Log.

Atenciosamente,
Equipe PrestaBR

**Comment by rafaelsilvabra** [comment]
Sobre os 3 erros de CPF: O Cliente é PJ. Ele informou: "senderCNPJ": "CNPJ_DELE", por isso o "creditCardHolderCPF": "" vazio e ai o erro?

Sobre os 8 erros segue log completo do último com erro.
![infos_log](https://user-images.githubusercontent.com/31866021/71105365-366dc600-219c-11ea-937a-bfcdd71122e9.jpg)

**Comment by prestabr** [comment]
Olá rafaelsilvabra,

> Sobre os 3 erros de CPF: O Cliente é PJ. Ele informou: "senderCNPJ": "CNPJ_DELE", por isso o "creditCardHolderCPF": "" vazio. Esse seria o erro?
> 
Sim, o CPF é sempre obrigatório, mesmo sendo PJ.

> Sobre os 8 erros segue log completo do último com erro.
> ![infos_log](https://user-images.githubusercontent.com/31866021/71105365-366dc600-219c-11ea-937a-bfcdd71122e9.jpg)

O Log está ok, todas as infos necesárias estão declaradas. A correção do bug na v.1.1.8 é para o pagamento/parcelamento em 1x, não se aplica ao seu pedido que está em 6x.

A api do getinstallmentes (mecanismo de parcelamento) está sofrendo alguma instabilidade intermitente, isso afetou o valor das parcelas, já estão trabalhando para normalizar o serviço.

Atenciosamente,
Equipe PrestaBR
