### ISSUE TITLE
Problemas para pagamento via cartão de credito

### ISSUE THREAD

**Issue by WebGF** [pagseguro/prestashop#76]
Ola, estamos tendo problema com o pagseguro checkout transparente 1.1.8 na plataforma do prestashop 1.6. Ao realizar a compra com o cartão de credito aparece a mensagem de “forma de pagamento indisponível...”. No log essa mesma compra esta aparecendo com o seguinte erro. Vocês sabem qual pode ser o problema ou como solucionar?
![esquina](https://user-images.githubusercontent.com/56832697/71674470-086eb100-2d5a-11ea-9c8a-60028aa94cfe.png)

![logAPIResposta](https://user-images.githubusercontent.com/56832697/71674480-10c6ec00-2d5a-11ea-8d35-8a788e628c76.png)

**Comment by prestabr** [comment]
Boa Tarde WebGF,

Tenta localizar a resposta da API no retorno do LOG, por favor, confere essa dica: https://github.com/pagseguro/prestashop/issues/75#issuecomment-567057058

Atenciosamente,
Equipe PrestaBR

**Comment by WebGF** [comment]
Boa tarde,
Seria esse log?
![Untitled-4](https://user-images.githubusercontent.com/56832697/71680985-4d9adf00-2d6a-11ea-9dc6-0b062d92724f.png)

**Comment by prestabr** [comment]
Olá WebGF,

Sim, é este Log, obrigado. Só por segurança, confere se o payload (dados enviados) estão com todas as informações necessárias, você pode tentar compará-lo com este issue: https://github.com/pagseguro/prestashop/issues/75#issuecomment-567127234

Atenciosamente,
Equipe PrestaBR

**Comment by WebGF** [comment]
Boa tarde Eu acho que todos os dados estão lá. Realmente realizei a atulização recentemente, mas todos os arquivos estão atualizados.
![cenc](https://user-images.githubusercontent.com/56832697/71682336-1d553f80-2d6e-11ea-8c74-b359146fa6f6.png)
