### ISSUE TITLE
Erro forma de pagamento indisponivel - UF ausente (null) no cadastro do cliente

### ISSUE THREAD

**Issue by alexweissweiss** [pagseguro/prestashop#78]
Olá, estou tendo o problema que vi em muitos relatos aqui, porém fiz todas as soluções propostas e nada ajudou. 
Agora veio a aparecer uma mensagem de erro apos salvar a configuração do modulo
![Capturar8](https://user-images.githubusercontent.com/61602988/76861265-143b2100-683b-11ea-892e-e3bb4480d7d3.JPG)

Alguem que possa me ajudar? Já estou a 1 semana quebrando cabeça com isso e nao tenho sucesso
![Capturar9](https://user-images.githubusercontent.com/61602988/76861407-55333580-683b-11ea-8c0a-9ae35a426361.JPG)

https://www.shoppingdoestudante.com/  link do meu site<<

uso prestashop 1.7.6.1 
Host: Umbler  PHP 7.0

**Comment by alexweissweiss** [comment]
O erro na linha 223 do arquivo corresponde ao seguinte:
		
linha222		if (((!$this->credentials['email'] || $this->credentials['email'] == '') || (!$this->credentials['token'] || $this->credentials['token'] == '')) 
linha223			|| ((!$this->credentials['appId'] || $this->credentials['appId'] == '') || (!$this->credentials['appKey'] || $this->credentials['appKey'] == '') || (!$this->credentials['authorizationCode'] || $this->credentials['authorizationCode'] == ''))
		) {

**Comment by prestabr** [comment]
Bom Dia alexweissweiss,

> Olá, estou tendo o problema que vi em muitos relatos aqui, porém fiz todas as soluções propostas e nada ajudou.
> Agora veio a aparecer uma mensagem de erro apos salvar a configuração do modulo
> ![Capturar8](https://user-images.githubusercontent.com/61602988/76861265-143b2100-683b-11ea-892e-e3bb4480d7d3.JPG)

Este popup indica apenas um warning, não impacta no funcionamento do módulo tanto no back quanto no frontoffice.

Antes de configurar o módulo e realizar testes de pagamento é importante desabilitar o debug da PrestaShop.

O módulo em modo de produção com a loja em modo debug acaba gerando problemas. O debug pode limitar a coleta de dados e redirecionamentos.

/config/defines.inc.php
/* Debug only */
if (!defined('PS_MODE_DEV')) {
define('PS_MODE_DEV', **false**);
}

> Alguem que possa me ajudar? Já estou a 1 semana quebrando cabeça com isso e nao tenho sucesso
> ![Capturar9](https://user-images.githubusercontent.com/61602988/76861407-55333580-683b-11ea-8c0a-9ae35a426361.JPG)
> 
> https://www.shoppingdoestudante.com/ link do meu site<<
> 
> uso prestashop 1.7.6.1
> Host: Umbler PHP 7.0

Esta mensagem de erro do PopUp é genérica, tem que conferir o payload/retorno nos Logs. Mais detalhes:

https://github.com/pagseguro/prestashop/issues/75#issuecomment-567057058 - Leia com calma, confere como verificar os logs.

Confere estes posts também:
https://github.com/pagseguro/prestashop/issues/58#issuecomment-536658104
https://github.com/pagseguro/prestashop/issues/58#issuecomment-545026313
https://github.com/pagseguro/prestashop/issues/74

Atenciosamente,
Equipe PrestaBR

**Comment by alexweissweiss** [comment]
Obtive os seguintes Logs:
Error
![Capturar10](https://user-images.githubusercontent.com/61602988/76865528-9deded00-6841-11ea-869a-ebe6141258b3.JPG)
![Capturar11](https://user-images.githubusercontent.com/61602988/76865533-9fb7b080-6841-11ea-95a3-e5363c496fc0.JPG)
 
CURL:
![Capturar12](https://user-images.githubusercontent.com/61602988/76865630-c4138d00-6841-11ea-9ab7-0b019ba4ead2.JPG)
![Capturar13](https://user-images.githubusercontent.com/61602988/76865639-c7a71400-6841-11ea-83c0-fda297250b50.JPG)


Seria então colocar um requerimento de UF do estado no endereço do cliente?

**Comment by prestabr** [comment]
Olá alexweissweiss,

> Obtive os seguintes Logs:
> Error
> ![Capturar10](https://user-images.githubusercontent.com/61602988/76865528-9deded00-6841-11ea-869a-ebe6141258b3.JPG)
> ![Capturar11](https://user-images.githubusercontent.com/61602988/76865533-9fb7b080-6841-11ea-95a3-e5363c496fc0.JPG)
> 
> CURL:
> ![Capturar12](https://user-images.githubusercontent.com/61602988/76865630-c4138d00-6841-11ea-9ab7-0b019ba4ead2.JPG)
> ![Capturar13](https://user-images.githubusercontent.com/61602988/76865639-c7a71400-6841-11ea-83c0-fda297250b50.JPG)
> 
> Seria então colocar um requerimento de UF do estado no endereço do cliente?

Sim, exatamente, o campo shippingAddressState (UF) está ausente (NULL) no cadastro do cliente.

Verifica se a UF está disponível no cadastro de cliente em sua loja: https://github.com/pagseguro/prestashop/issues/58#issuecomment-545026313

Atenciosamente,
Equipe PrestaBR

**Comment by alexweissweiss** [comment]
A principio era isso! adicionei um requerimento de Estado no endereço do cliente e no teste seguinte funcionou.

Vou continuar fazendo testes mas obrigado pela ajuda! 
Segue o log da compra: 
![Capturar14](https://user-images.githubusercontent.com/61602988/76867396-3b4a2080-6844-11ea-990e-143067a94d76.JPG)
![Capturar15](https://user-images.githubusercontent.com/61602988/76867408-3dac7a80-6844-11ea-9615-b02e86b4aee8.JPG)
![Capturar16](https://user-images.githubusercontent.com/61602988/76867415-400ed480-6844-11ea-8b27-7dafcdd3171c.JPG)

aparentemente tudo ok correto?  
Mais uma coisa, o produto cusa R$5,50  e no boleto gerado o valor ficou de R$6,50 
pode me explicar o porque desse acrécimo já no boleto?

**Comment by prestabr** [comment]
Olá alexweissweiss,

> A principio era isso! adicionei um requerimento de Estado no endereço do cliente e no teste seguinte funcionou.
> 
> Vou continuar fazendo testes mas obrigado pela ajuda!
> Segue o log da compra:
> ![Capturar14](https://user-images.githubusercontent.com/61602988/76867396-3b4a2080-6844-11ea-990e-143067a94d76.JPG)
> ![Capturar15](https://user-images.githubusercontent.com/61602988/76867408-3dac7a80-6844-11ea-9615-b02e86b4aee8.JPG)
> ![Capturar16](https://user-images.githubusercontent.com/61602988/76867415-400ed480-6844-11ea-8b27-7dafcdd3171c.JPG)
> 
> aparentemente tudo ok correto?

Sim, está perfeito! Desejamos Boas Vendas! :)

> Mais uma coisa, o produto cusa R$5,50 e no boleto gerado o valor ficou de R$6,50
> pode me explicar o porque desse acrécimo já no boleto?

Essa taxa de R$ 1,00 é o que está descrito na tela de configuração do módulo:

![Screenshot at 2020-03-17 11-41-59](https://user-images.githubusercontent.com/7054224/76867906-ece95180-6844-11ea-95ff-8703b6d10f04.png)

Atenciosamente,
Equipe PrestaBR

**Comment by alexweissweiss** [comment]
Ok, entendido. 

Obrigado pela ajuda, e com o problema do UF. eu estava olhando para este lado, mas Faltava uma luz pra direcionar ao lugar certo e resolver a situação.
Muito obrigado.  
Att: Alex Weiss
