### ISSUE TITLE
PS 1.7 - Módulo pagseguro não aparece no checkout (transportadora não vinculada à forma de pagamento no backoffice)

### ISSUE THREAD

**Issue by ctmdeshop** [pagseguro/prestashop#79]
Na versão 1.7.6.4 ao instalar o módulo, o mesmo acopla ao back office, porém não aparece na tela de checkout. 

Achei que o problema fosse com o existência de OnePage Checkout, mas desativei e deixei o modo normal do prestashop nativo, e mesmo assim não funcionou.

**Comment by prestabr** [comment]
Boa Tarde ctmdeshop,

Não conseguimos reproduzir este problema na versão mais recente da PrestaShop (v. 1.7.6.4) em nosso ambiente de testes e homologações.

**Importante**

Como analisar se a integração está funcional (mesmo procedimento para PS 1.6 e 1.7):

https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Como analisar logs:

https://github.com/pagseguro/prestashop/issues/75#issuecomment-567057058 (Leia com calma, confere como verificar os logs)

Já conferiu esta issue? É possível que seja o mesmo problema:
https://github.com/pagseguro/prestashop/issues/60#issuecomment-540640441

Atenciosamente,
Equipe PrestaBR

**Comment by ctmdeshop** [comment]
Segue abaixo as credenciais de acesso para análise do problema com o módulo. 
As mesmas estarão ativas por 48h

URL: www.ctmdeshop.com/office
user: sac@prestabr.com.br
password: 123456789

**Comment by prestabr** [comment]
Olá ctmdeshop,

> Segue abaixo as credenciais de acesso para análise do problema com o módulo.
> As mesmas estarão ativas por 48h
> 
> URL: [www.ctmdeshop.com/office](http://www.ctmdeshop.com/office)
> user: [sac@prestabr.com.br](mailto:sac@prestabr.com.br)
> password: 123456789

É exatamente a mesma questão da issue https://github.com/pagseguro/prestashop/issues/60#issuecomment-540640441

Utilizando a PrestaShop 1.7, acesse no Back Office a tab "Pagamento > Preferências > Restrições de transportadora" e verifique se as transportadoras estão vinculadas à forma de pagamento.

![Screenshot at 2020-03-17 17-31-31](https://user-images.githubusercontent.com/7054224/76899268-f6d77880-6875-11ea-9584-e5a22ed675db.png)

Atenciosamente,
Equipe PrestaBR
