### ISSUE TITLE
Módulo 1.7 não instala

### ISSUE THREAD

**Issue by rogernascimento** [pagseguro/prestashop#81]
Olá!
Tenho uma loja Prestashop versão 1.6.1.17 e está instalado o módulo padrão que veio na loja do PagSeguro.
Este módulo começou a não funcionar de uns dias para cá, resolvi tentar instalar a versão 1.7 deste módulo aqui do git.
Não desinstalei a versão que estava padrão (imagino que por serem instaladas em pastas diferentes não haverá problema).
Contudo aparece a informação de erro abaixo

Alguém poderia me ajudar?

Erro que aparece

[PrestaShop] Fatal error in module file :/home/storage/6/51/05/.../modules/pagseguropro/pagseguropro.php:
Call to undefined method PagSeguroPro::trans()

**Comment by prestabr** [comment]
Boa Noite rogernascimento,

> Olá!
> Tenho uma loja Prestashop versão 1.6.1.17 e está instalado o módulo padrão que veio na loja do PagSeguro.
> Este módulo começou a não funcionar de uns dias para cá, resolvi tentar instalar a versão 1.7 deste módulo aqui do git.

Você está tentando usar o módulo da 1.7 na versão 1.6 da PrestaShop?

Módulo p/ PS 1.6 (v.1.1.8): https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro

Módulo p/ PS 1.7 (v.1.0.3): https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro

> Não desinstalei a versão que estava padrão (imagino que por serem instaladas em pastas diferentes não haverá problema).
> Contudo aparece a informação de erro abaixo
> 
> Alguém poderia me ajudar?
> 
> Erro que aparece
> 
> [PrestaShop] Fatal error in module file :/home/storage/6/51/05/.../modules/pagseguropro/pagseguropro.php:
> Call to undefined method PagSeguroPro::trans()


Manter os 2 módulos ativos e em funcionamento pode gerar algum conflito, o ideal é utilizar somente um deles. Os módulos disponíveis aqui no Git para PS 1.6 e 1.7 são os oficiais do PagSeguro.

Antes de instalar o módulo verifique se as permissões das pastas e arquivos em sua hospedagem estão funcionando 100%. O ideal é 755 para pastas e 644 para arquivos.

Atenciosamente,
Equipe PrestaBR

**Comment by rogernascimento** [comment]
A instalação deu certo! Escolhi, agora, a versão 1.6. Apareceu um erro na tentativa de concluir um pagamento, vou procurar se há algum issue sobre o tema, senão abrirei.
Obrigado!!!
