### ISSUE TITLE
Forma de pagamento temporariamente indiponível. Por favor, ...

### ISSUE THREAD

**Issue by rogernascimento** [pagseguro/prestashop#82]
Boa noite!!!
Tenho uma loja PrestaShop versão 1.6.1.17
Tenho o módulo do PagSeguro configurado para receber em Cartão e Boleto.
Estou tentando um pagamento em cartão e está retornando o erro mencionado no título deste issue.
Segue o log.
Obrigado desde já!!!

![Err](https://user-images.githubusercontent.com/21369782/78845769-8c7aa980-79d7-11ea-84a5-97367cb2044b.png)

**Comment by prestabr** [comment]
Boa Noite rogernascimento,

Pra identificar a origem do problema você precisa localizar a resposta da API deste log.

https://github.com/pagseguro/prestashop/issues/75#issuecomment-567057058 - Leia com calma, confere como verificar os logs e localizar a resposta da API.

Confere estes posts também:
https://github.com/pagseguro/prestashop/issues/58#issuecomment-536658104
https://github.com/pagseguro/prestashop/issues/58#issuecomment-545026313
https://github.com/pagseguro/prestashop/issues/74

Atenciosamente,
Equipe PrestaBR

**Comment by rogernascimento** [comment]
Bom dia!!! Obrigado pelo rápido retorno.
Encontrei o arquivo que dizia que o valor total do carrinho era negativo.
Estou analisando!

**Comment by prestabr** [comment]
Boa Tarde rogernascimento,

Ótimo! Isto é uma regra da API, não processar pedido com produto que tenha o valor igual a zero (grátis), onde o cliente para somente o frete ou, o pedido inteiro grátis. Nestes casos o ideal é você aplicar um voucher no carrinho, se o produto custar R$ 1,00 o pedido já é processado normalmente.

Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
