### ISSUE TITLE
Pedido Grátis & Termos de Serviço

### ISSUE THREAD

**Issue by zagalux** [pagseguro/prestashop#83]
Tenho itens digitais grátis na minha loja que custam 0, e quando o cliente tenta processar o pagamento que o total do pedido da 0 o pagseguro não libera a transação, ele bloqueia o botão para finalizar o checkout pois da erro para carregar os métodos de pagamento já que não aceitam o total 0.

 Tem algum meio de fazer o módulo não carregar quando o total é 0?

 O prestashop em sozinho desabilita todos os meios de pagamento quando o total é 0, porém o pagseguro não entra como método de pagamento em módulos para o prestashop.

Versão prestashop: 1.7.6.0
Versão checkout transparente: 1.0.3

**Comment by prestabr** [comment]
Boa Tarde zagalux,

Existe o total de produtos e o total do pedido (produto + frete). Se o total de produtos for igual a zero, onde o cliente paga somente o frete, a API de pagamentos não aceita e não processa o pedido. Para o total do pedido igual a zero a PrestaShop remove todas as opções de pagamento e deixa o cliente fazer um pedido grátis, sem processar qualquer informação externa.

Um exemplo: Se no seu carrinho de compras você estiver com mais de um produto, um grátis pra download e outro que custa R$ 1,00, a PrestaShop vai exibir o módulo de pagamento e o cliente não vai conseguir pagar porque um dos produtos é grátis.

> Tenho itens digitais grátis na minha loja que custam 0, e quando o cliente tenta processar o pagamento que o total do pedido da 0 o pagseguro não libera a transação, ele bloqueia o botão para finalizar o checkout pois da erro para carregar os métodos de pagamento já que não aceitam o total 0.

Se o meio de pagamento estiver sendo exibido significa que não é um pedido grátis.

> 
> Tem algum meio de fazer o módulo não carregar quando o total é 0?
> 

O PrestaShop já faz isso para todas as soluções de pagamento instaladas, desde que o pedido seja grátis.

> O prestashop em sozinho desabilita todos os meios de pagamento quando o total é 0, porém o pagseguro não entra como método de pagamento em módulos para o prestashop.

Não entendi a questão, mas você pode gerenciar as configurações dos meios de pagamentos instalados acessando "Pagamentos > Preferências". No menu "Pagamentos > Métodos de Pagamento", são exibidos somente módulos nativos ou módulos que são oferecidos na loja Addons da PrestaShop.

> Versão prestashop: 1.7.6.0
> Versão checkout transparente: 1.0.3

Resumindo, fizemos alguns testes do nosso lado e verificamos que quando a opção "Termos de Serviço" (Menu "Parâmetros da Loja > Opções de Pedidos > Termos de Serviço") está desabilitada, o botão para realizar o pedido fica desativado. Não é algo relacionado ao módulo de pagamento, você pode testar desabilitando o módulo e verificar que o problema persiste.

O ideal é sinalizar para a própria PrestaShop sobre essa questão do pedido grátis e os termos de serviço, ou aguardar a próxima update.

Atenciosamente,
Equipe PrestaBR

**Comment by zagalux** [comment]
O módulo funciona normalmente quando o valor do pedido é maior que 0.
Apenas quando o total do pedido é 0, produto e frete grátis, o módulo do pagseguro tenta retornar, aparece uma mensagem 0 e o botão de finalizar o pedido fica desabilitado.

O módulo do pagseguro não aparece como extensão de pagamento, e sim como uma extensão extra, ele está sendo carregado a parte dos pagamentos do prestashop, meus outros pagamentos ficam desabilitados normalmente quando o total é 0.

**Comment by prestabr** [comment]
Olá zagalux,

**Comment by zagalux** [comment]
Realmente, desabilitei o pagseguro e o problema é o termos de serviço.

obrigado

**Comment by prestabr** [comment]
Olá zagalux,

> O módulo funciona normalmente quando o valor do pedido é maior que 0.
> Apenas quando o total do pedido é 0, produto e frete grátis, o módulo do pagseguro tenta retornar, aparece uma mensagem 0 e o botão de finalizar o pedido fica desabilitado.

Chegou a conferir a mensagem abaixo? Faça o teste se possível...

Resumindo, fizemos alguns testes do nosso lado e verificamos que quando a opção "Termos de Serviço" (Menu "Parâmetros da Loja > Opções de Pedidos > Termos de Serviço") está desabilitada, o botão para realizar o pedido fica desativado. Não é algo relacionado ao módulo de pagamento, você pode testar **desabilitando** o módulo e verificar que o problema persiste.

> O módulo do pagseguro não aparece como extensão de pagamento, e sim como uma extensão extra, ele está sendo carregado a parte dos pagamentos do prestashop, meus outros pagamentos ficam desabilitados normalmente quando o total é 0.

O módulo não é exibido em  "Pagamentos > Preferências". No menu "Pagamentos > Métodos de Pagamento" porque ele não é nativo da PrestaShop e também não é oferecido na loja Addons. É uma regra da PrestaShop...

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Olá zagalux,

> Realmente, desabilitei o pagseguro e o problema é o termos de serviço.
> 
> obrigado

Exatamente... Obrigado por testar e confirmar.

Infelizmente a PS 1.7 ainda apresenta muitos bugs e sofre constantes updates. Se puder sinalizar essa questão para eles talvez ela seja corrigida na próxima relase.

Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR

**Comment by zagalux** [comment]
Vou sinalizar, porém eu tinha deixado desabilitado por um problema com o pagemento em cartão:

Caso alguem não preencha algum dado do cartão mas já tenha clicado em aceitar termos e condições, caso a pessoa volte a preencher os dados alertados o botão para finalizar fica bloqueado a não ser que a pessoa "destique" e tique a caixa do termos e serviço novamente, tem como o módulo quando receber um erro "desticar" o box?

**Comment by zagalux** [comment]
Mesmo quando habilitado ele aparece um 0 como resposta do pagseguro, como desabilitar essa mensagem ao usuario?

**Comment by prestabr** [comment]
Olá zagalux,

> Vou sinalizar, porém eu tinha deixado desabilitado por um problema com o pagemento em cartão:
> 
> Caso alguem não preencha algum dado do cartão mas já tenha clicado em aceitar termos e condições, caso a pessoa volte a preencher os dados alertados o botão para finalizar fica bloqueado a não ser que a pessoa "destique" e tique a caixa do termos e serviço novamente, tem como o módulo quando receber um erro "desticar" o box?

Já vimos esta questão também, este recurso/botão do termos de serviço é uma coisa não muito bem resolvida na PS 1.7.

Lembra? https://github.com/pagseguro/prestashop/issues/63

Se a gente colocar essa opção de desmarcar o checkbox podemos causar problemas com outras soluções ou até um conflito com o próprio JavaScript da PrestaShop na tela de checkout.

Você pode resolver isso pra necessidade da sua loja... Faz o seguinte...:

a) Desativa os termos de serviço em "Parâmetros da Loja > Opções de Pedidos > Termos de Serviço".

b) Ajustando o layout, acessa o arquivo e remove a linha em destaque, salva o arquivo e limpa o cache da loja.

/themes/classic/templates/checkout/_partials/steps/payment.tpl

![Screenshot at 2020-04-27 14-27-34](https://user-images.githubusercontent.com/7054224/80401944-89b2fc00-8893-11ea-9dda-fe0c6ef33955.png)

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Olá zagalux,

> Mesmo quando habilitado ele aparece um 0 como resposta do pagseguro, como desabilitar essa mensagem ao usuario?

Podemos analisar e realizar alguns testes para essa questão específica. Se a gente conseguir reproduzir e não depender de ajustes na plataforma estaremos lançando na próxima versão do módulo.

Atenciosamente,
Equipe PrestaBR

**Comment by zagalux** [comment]
Deu certo, muito obrigado, só ficou mesmo essa questão do 0 que aparece após carregar o módulo do pagseguro.

Muito obrigado
