### ISSUE TITLE
Preenchimento automático do CPF

### ISSUE THREAD

**Issue by glaucomodera** [pagseguro/prestashop#84]
Olá pessoal, 
Tenho um módulo de cadastro em meu site (Verção 1.7). Esse módulo permite cadastro do CPF. 
Pois bem, acontece que quando o cliente vai pagar via cartão ou boleto o módulo pagseguro absorve o número do celular e já aparece o número "digitado", mas não absorve o CPF. Eu olhei na programação de vocês e percebi que existe uma chamada para o boleto_doc ou card_doc mas ele busca essa informação onde? Pois no prestashop defull não tem esse campo. Então eu acredito que vocês estão apontando essa chamada para algum lugar. 
Me perdoe, mas eu não sou programador então talvez, se vocês me derem uma resposta simples e depois uma outra resposta técnica eu vou conseguir pesquisar a respeito. Abraços.

**Comment by prestabr** [comment]
Boa Noite Glauco,

Se o CPF não é exibido, automaticamente, no campo indicado na tela de checkout, significa que talvez a sua loja não esteja adaptada para o padrão de cadastro brasileiro, que incluí e torna obrigatório o preenchimento do CPF/RG na tela de cadastro do cliente em sua loja.

Os módulos de integração do PagSeguro pra PrestaShop 1.6 e 1.7 são compatíveis com os principais módulos de cadastro brasileiro. Você utiliza já algum módulo para esta finalidade?

Tecnicamente esses módulos cadastram o CPF/RG na tabela ps_customer. Eventualmente, se você lançar alguma customização em override para adaptadar o seu mecanismo de cadastro é só add o campo com o nome "cpf" e "rg" nesta tabela.

Atenciosamente,
Equipe PrestaBR

**Comment by glaucomodera** [comment]
Olá, obrigado pelo rápido retorno. Eu uso o módulo da NeoGest e deixei obrigatório o cadastro com CPF. Inclusive está funcionando perfeitamente. Se um cliente acessa meu site por meio de uma rede social, antes de iniciar o checkout o módulo solicita o CPF via modal. 
O único incoveniente é que na hora de pagar ele tem que digitar o CPF novamente. 
Até agora nenhum cliente reclamou, mas é capaz de eu estar perdendo venda por tornar o pagamento menos amigável.

**Comment by glaucomodera** [comment]
Eu localizei ele aqui no PS_costumer... 
- ngstandard_document_number
- ngstandard_cpf
o CPF aparece tanto em um como no outro

**Comment by glaucomodera** [comment]
- 1. - ngstandard_document_number
- 2. - ngstandard_cpf

**Comment by prestabr** [comment]
Olá Glauco,

Obrigado pelo feedback e por utilizar nossas soluções!

Ótimo que ativou a obrigatoriedade do CPF, isso é importante.

Segunda-feira agora estaremos lançando uma upgrade nos módulos da 1.6 e 1.7 e, isso incluí a compatibilidade com o módulo ngstandard e outros 3 módulos gratuitos da web. Também estaremos abrindo a opção de configurar o valor da parcela mínima aceita pela loja, entre outras melhorias e correções menores de bugs.

Vamos deixar o issue aberto, assim que subirmos a upgrade te avisamos por aqui.

Se cuida por aí e boas vendas! :)

Atenciosamente,
Equipe PrestaBR

**Comment by glaucomodera** [comment]
Mano!!! Excelente notícia. Obrigado por se importarem conosco e escutar a voz dos vendedores. 
Os campos da ngstandart são: 

- ngstandard_document_number
- ngstandard_cpf

Fico no aguardo do upgrade então. Abraços.

**Comment by glaucomodera** [comment]
Se possível, altere o campo data de nascimento para texto e não como data, pois no celular aparece um calendário gigantesco e os clientes têm dificuldade de selecionar o ano e o mês, pois fica muito estranho. Coloquem em formato de texto mas com o auto preenchimento das barras DD/MM/AAA

**Comment by prestabr** [comment]
Boa Tarde Glauco,

Só informando, os módulos p/ 1.6.x e 1.7.x estão atualizados e disponíveis aqui no Git.

Changelog:

PS 1.6.x: https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#changelog

PS 1.7.x: https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#changelog

Ambos os módulos agora são compatíveis com o ngstandard. Também alteramos o formato do preenchimento da data no cartão de crédito e para o caso de produtos virtuais ocultamos o alerta na tela de checkout.

Para atuaizar o módulo em sua loja 1.7.x você pode serguir o passo-a-passo de instalação: https://github.com/pagseguro/prestashop#instala%C3%A7%C3%A3o---prestashop-17x

Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR

**Comment by glaucomodera** [comment]
Pessoal... simplesmente ficou muito Toooooooppppppp
Parabéns a vocês!!!!
