### ISSUE TITLE
1.7 - "ReferenceError: urlImg is not defined"

### ISSUE THREAD

**Issue by glaucomodera** [pagseguro/prestashop#85]
Boa noite pessoal do PrestaBR. 

Parabéns pelo excelente trabalho...

Uma dúvida... Estou no presta 1.7.6.3

Se no console der esse erro devo ignorar -  se o módulo funcionar normalmente?
![errojs](https://user-images.githubusercontent.com/56834125/80930798-2d1c7900-8d8c-11ea-85b0-585bff6c8f3d.JPG)

Todas essas linhas estão no js do pagseguro.  Sem o pagseguro esse erro no console não aparece.

**Comment by prestabr** [comment]
Boa Tarde Glauco,

Obrigado pelo feedback! :)

Esse erro no console do seu navegador indica que pode existir algum conflito de JavaScript em sua loja. A origem do problema pode estar em algum arquivo JavaScript do tema ou módulos.

Imagina que o JavaScript funciona dessa forma:

Processo A - arquivos .js do tema
Processo B - arquivos .js externos
Processo C - arquivos .js do módulo pagseguropro

Se algum conflito existir no processo A ou B o processo C não vai funcionar direito e vai apresentar problema.

Esse parâmetro específico fica no tema "/pagseguropro/views/templates/hook/payment_top.tpl". Ele é importante para exibir a bandeira do cartão de crédito durante a digitação na tela de pagamento.

Cria um backup da sua loja e faz um ambiente de testes pra você poder debugar tranquilo, exemplo: minhaloja.com.br/minhalojateste

Atenciosamente,
Equipe PrestaBR

**Comment by glaucomodera** [comment]
Olá, eu estou migrando do 1.6 para 1.7 e já estou fazendo os testes aqui para migrar e deixar o pagamento liso.
Esse erro aparece no pagamento, nas abas 1) Informações Pessoais e 2) Endereços. 
Quando eu avanço para a aba 3) Metodo de envio o erro não aprece mais no console. O mesmo acontece quando carrega a aba 4) Pagamento. 

Esse erro tem algo a ver com a UrlImg, pois na programação do pagseguro tem uma chamada para Url_img

![payment_top_plp](https://user-images.githubusercontent.com/56834125/81002839-453dd800-8e20-11ea-92a4-36be491d9626.JPG)

**Comment by prestabr** [comment]
Olá Glauco,

O módulo do pagseguropro depende essencialmente de JavaScript para funcionar, ele é sensível à erros e falhas de terceiros em sua loja. Neste formato...:

Imagina que o JavaScript funciona dessa forma:

Processo A - arquivos .js do tema
Processo B - arquivos .js externos
Processo C - arquivos .js do módulo pagseguropro

Se algum conflito existir no processo A ou B o processo C não vai funcionar direito e vai apresentar problema.

Podemos te assegurar que o erro não é no código do módulo, não conseguimos reproduzir em outras lojas em produção (várias an 1.6 e 1.7) e em nosso ambiente de testes e homologações.

JavaScript é trabalhoso de depurar e normalmente exige paciência/experiência, mas neste caso o erro surge direto no seu console, fica mais fácil de tentar resolver. Tenta desativar o CCC do JS, geralmente quando tem conflito a compressão não fica legal. Acessa "Parâmetros Avançados > Desempenho > CCC (Combinação, Compressão e Cache)".

Atenciosamente,
Equipe PrestaBR

**Comment by glaucomodera** [comment]
Olá, meus queridos... vou fazer um teste aqui no modo produção e vou torcer pra funcionar, pois não sou programador. O que vocês escreveram aí deu até uma luz, mas como eu não manjo nada, tenho medo de entrar nessa programação marota. 
Obrigado por hora.

**Comment by prestabr** [comment]
Olá Glauco,

Entendo, fazer os testes em produção pode ser arriscado se alguma coisa parar de funcionar.

O problema está relacionado ao módulo mas não é originado por ele. Sendo algo no módulo a gente resolvia e atualizava aqui no Git...!

Esse erro não interfere no processamento da transação em sí. Você comentou que o erro não aparece na tela de pagamento, mas isso não faz nenhum sentido porque é justamente lá que deveria aparecer. Isso parece ser algo relacionado a cache.

Fizemos um teste navegando até o checkout, nenhum erro apareceu no console e ao digitar o cartão foi identificada a bandeira normalmente.

![Screenshot at 2020-05-05 10-12-51](https://user-images.githubusercontent.com/7054224/81070212-4d962180-8eb9-11ea-9c6e-4d9e400849c8.png)

Boas Vendas...!

Atenciosamente,
Equipe PrestaBR

**Comment by glaucomodera** [comment]
O site que estou desenvolvendo é:
https://dev.modera.com.br

**Comment by evandroliberato** [comment]
> O site que estou desenvolvendo é 1.7 e está em outro endereço:
> https://dev.modera.com.br

Você conseguiu alguma solução pra esse problema, estou com o mesmo problema.

**Comment by glaucomodera** [comment]
olá... sim... problema resolvido há tempos..

**Comment by glaucomodera** [comment]
De qualquer forma eu não conseguiria ajudar, pois eu já fiz muitos updates no módulo, migrei de servidor, repaginei meu site. Atualizei prestashop por duas vezes. Então eu não consigo lembrar qual foi a solução.

**Comment by evandroliberato** [comment]
> De qualquer forma eu não conseguiria ajudar, pois eu já fiz muitos updates no módulo, migrei de servidor, repaginei meu site. Atualizei prestashop por duas vezes. Então eu não consigo lembrar qual foi a solução.

Entendi, muito obrigado pela resposta. 
abraço!
