### ISSUE TITLE
Traduções

### ISSUE THREAD

**Issue by glaucomodera** [pagseguro/prestashop#86]
Boa tarde amigos. 

Mais uma vez estou aqui pedindo auxílio. 

Seguinte, quando eu digito o código de segurança errado, dá a seguinte mensagem: "security field with invalid length". Quando eu digito o cartão errado "invalid creditcard data". 

Como traduzir isso? já fui em todas as opções de tradução e não encontrei essa frase. Como não encontrei essa frase para traduzir no módulo pagseguropro, fui na raíz da pasta e não encontrei nenhum arquivo com essa frase para eu substituir.

**Comment by prestabr** [comment]
Boa Tarde Galuco,

Essa tradução não faz parte do módulo, os alertas impressos na tela são sempre em pt-br indicados no arquivo pagseguropro.js.

Alguma coisa deve ter dado errado aí... Vc deveria ver algo do tipo:

![Screenshot at 2020-05-05 17-00-21](https://user-images.githubusercontent.com/7054224/81111540-a08cca80-8ef3-11ea-9da3-5d4da793f1a5.png)

Você mais detalhes sobre? Tem algum print ou log?

Atenciosamente,
Equipe PrestaBR

**Comment by glaucomodera** [comment]
Olá as vezes aparece a mensagem em inglês, a maioreia das vezes a mensagem está em portugues. Mas por exemplo, se você digitar o CVV errado, a mensagem vai dar em ingles.

**Comment by prestabr** [comment]
Olá Glauco,

Este problema é bem estranho, não tem lógica ter essa intermitência na tradução. Infelizmente, não conseguimos reproduzir em nosso ambiente de testes.

Recomendamos que você procure um profissional para te auxiliar no desenvolvimento da sua nova loja na versão 1.7 da PrestaShop.

Atenciosamente,
Equipe PrestaBR
