### ISSUE TITLE
Formatação Template Nobo

### ISSUE THREAD

**Issue by glaucomodera** [pagseguro/prestashop#87]
Olá pessoal, 
Recentemente eu adquri um template novo em meu site. 
Acontece que, quando instalo o módulo de vocês, o layout fica todo bugado...
Ao pagar via cartão, os caracteres somem, os campos ficam todos desalinhados. 
A única maneira de eu fazer o módulo se ajustar ao meu template é configurando o CSS e os TPL do cartão e Boleto.
Não existe um tipo de configuração padrão que adere a qualquer tipo de template?

**Comment by glaucomodera** [comment]
[arquivos_editados.zip](https://github.com/pagseguro/prestashop/files/4583484/arquivos_editados.zip)
Segue os arquivos editados para vocês terem uma referência para uma possível atualização futura. 
Os arquivos que eu sempre altero quando vocês lançam um novo update são:
pagseguropro.css, boleto.tpl e cartão.tpl

**Comment by prestabr** [comment]
Boa Tarde Glauco,

O módulo não instala override, nem bilbiotecas externas, exige poucos recursos da Hospedagem/Plataforma, é o mais leve e limpo possível.

Se você comprar um layout muito modificado, sem qualidade técnica (o que é comum), com muitas alterações de TPL, CSS e JS é possível algumas coisas dêem problemas diversos.

Já vimos alguns temas, como o warehouse por exemplo, que de forma arbitrária sobreescreve todo o CSS que estiver na zona de checkout, inutilizando o CSS customizado do módulo deixando o layout todo bugado - talvez seja o seu caso de agora.

Garatimos o perfeito funcionamento do módulo na loja padrão da PrestaShop, tanto na 1.6.x quanto na 1.7.x, em ambiente de Testes e Homologações antes de disponibilizar aqui no GitHub, livres de interferências de terceiros. Se você instalar uma loja limpa na versão 1.6.x ou 1.7.x da PrestaShop verá o módulo funcionando normalmente.

A PrestaShop 1.7.x é mais complicada pra depurar e ajustar layout, tema, etc do que a 1.6.x. Recomendamos que você procure um profissional para te auxiliar no desenvolvimento da sua nova loja na versão 1.7.x da PrestaShop.

Atenciosamente,
Equipe PrestaBR

**Comment by glaucomodera** [comment]
Isso mesmo... eu estou no wharehouse .. mas tá tudo certo. Estou modificando aqui e está ficando bom... Obrigado...
