### ISSUE TITLE
Fica na tela "carregando" um "relógio girando o ponteiro" mas não carrega (PrestaShop 1.6.1.24 com php 7.1, Function mcrypt_encrypt() is deprecated /classes/Rijndael.php on line 51)

### ISSUE THREAD

**Issue by rogernascimento** [pagseguro/prestashop#88]
Boa tarde!
Não está carregando o passo de pagar no PagSeguro.
Minha loja é 1.6.1.24
Lá em Pedidos / PagSeguro Logs aparece a seguinte mensagem

RESPOSTA DA API
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<session>
  <id>83a5e3afa62f45c48d9cd6ec1e7630e7</id>
</session>

**Comment by prestabr** [comment]
Boa Tarde rogernascimento,

Você está conferindo o Log errado... Faz o seguinte, confere essa dica:

https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Abrindo o console do seu navegador, se houver um erro, tira um print e posta aqui pra gente te ajudar.

Já conferiu estes posts? https://github.com/pagseguro/prestashop/issues/49

Atenciosamente,
Equipe PrestaBR

**Comment by rogernascimento** [comment]
Obrigado!
Segue um print.
![Erro](https://user-images.githubusercontent.com/21369782/81603809-f1da0580-939c-11ea-9eb5-98973c58dd06.png)

**Comment by prestabr** [comment]
Olá rogernascimento,

Este erro "Unexpected token < in json at position 0" é bem genérico e geralmente indica algum conflito de JavaScript no layout da sua loja.

Nesta issue você havia comentado que chegou até a tela de checkout. https://github.com/pagseguro/prestashop/issues/81

Recentemente, você instalou algum script ou módulo de terceiro em sua loja? Isso pode estar causando o conflito que gera o travamento do módulo de pagamento.

Confere essas dicas:

a) Acessa as configurações do módulo e, verifica se a opção "Exibir parâmetros no Console do navegador?" está habilitada. Confere essas orientações: https://github.com/pagseguro/prestashop/blob/master/1.7.x/checkout-transparente/pagseguropro/Readme.md#6---debug-para-solu%C3%A7oes-de-problemas

b) Verifique se o token é de produção e o ambiente também;

c) Verifique se as tabelas do banco de dados "ps_pagseguropro" e "ps_pagseguropro_logs" estão corretamente instaladas;

d) Verifique se as permissões dos arquivos em sua hospedagem estão configuradas corretamente, o ideal é 755 para diretórios e 644 para arquivos.

e) Acesse no Back Office a tab “Parâmetros Avançados > Desempenho > CCC (COMBINAÇÃO, COMPRESSÃO E CACHE)”.

Marque as opções “Cache inteligente para JavaScript”, “Comprimir JavaScript inline em
HTML” e “Mover o JavaScript para o final” como Não. Também limpe o cache no botão que fica no canto superior direito dessa tab, com o nome "Limpar cache".

É comum tem algum detalhe de JavaScript customizado no tema da loja, que não segue as melhores práticas de desenvolvimento, e acabam não suportanto as otmizações que o CCC proporcionam - gerando conflitos diversos e travamentos diversos.

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Olá rogernascimento,

Estes erros são problemas de configuração de hospeagem que afetam a Plataforma PrestaShop como um todo, além do módulo de pagamento no checkout.

> <b>Warning</b>:  Use of undefined constant _RIJNDAEL_KEY_ - assumed '_RIJNDAEL_KEY_' (this will throw an Error in a future version of PHP) in <b>/home/storage/6/51/05/glendaroberta/public_html/decoraquadros/classes/Cookie.php</b> on line <b>79</b><br />
> <b>Warning</b>:  Use of undefined constant _RIJNDAEL_IV_ - assumed '_RIJNDAEL_IV_' (this will throw an Error in a future version of PHP) in <b>/home/storage/6/51/05/glendaroberta/public_html/decoraquadros/classes/Cookie.php</b> on line <b>79</b><br />
> <b>Warning</b>:  Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' (this will throw an Error in a future version of PHP) in <b>/home/storage/6/51/05/glendaroberta/public_html/decoraquadros/classes/Rijndael.php</b> on line <b>124</b><br />
> <b>Warning</b>:  openssl_decrypt(): IV passed is only 7 bytes long, cipher expects an IV of precisely 16 bytes, padding with \0 in <b>/home/storage/6/51/05/glendaroberta/public_html/decoraquadros/classes/Rijndael.php</b> on line <b>91</b><br />

Recentemente você deve ter atualizado a versão da sua loja pra 1.6.1.24 e a do php para 7.0 ou 7.1, confere?

Na versão 1.6.1.24 com o php 7.x algumas coisas mudaram e alguns problemas de compatibilidade podem surgir. Para resolver, faz o seguinte:

Acessa o banco de dados da sua loja, na tabela "ps_configuration", localiza o campo "PS_CIPHER_ALGORITHM" e assinala como "0". Exemplo:

SELECT * FROM `ps_configuration` WHERE name='PS_CIPHER_ALGORITHM';

![Screenshot at 2020-05-11 19-02-48](https://user-images.githubusercontent.com/7054224/81616550-10022e80-93ba-11ea-80da-2ffbfd33971e.png)

UPDATE `ps_configuration` set value=0 WHERE name='PS_CIPHER_ALGORITHM';

Desejamos Boa Sorte e Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR

**Comment by rogernascimento** [comment]
Muito obrigado!
Isto mesmo, migramos para a 1.6.1.24 e php 7.1.
Fiz o que solicitou! Olhe o print.
Mas... deram duas piscadas, duas travadas, parecia que iria, mas não foi!
![Erro_03](https://user-images.githubusercontent.com/21369782/81619226-1a6ef900-93b7-11ea-9c77-4dc47922ab6b.png)

**Comment by prestabr** [comment]
Olá rogernascimento,

O ideal é que você use o PHP 7.0 ou 7.0.33 com a PrestaShop 1.6.1.24. Com o PHP 7.1 até 7.4 vários outros problemas surgirão. Se não puder voltar pro PHP 7.0.x talvez seja mais fácil atualizar a PrestaShop pra 1.7.

Atenciosamente,
Equipe PrestaBR
