### ISSUE TITLE
Pedido com informações de endereço de entrega faltando

### ISSUE THREAD

**Issue by lucasdamo** [pagseguro/prestashop#89]
Quando eu instalei o módulo do PagSeguro algo não permitia a conclusão do pagamento. Mensagens genéricas como: "Método de pagamento indisponível" apareciam na tela após o envio das informações do cartão de crédito.

Após debugar um pouco, percebi que o motivo da recusa era a falta de estado no endereço de entrega (ex: RJ) , então o tornei obrigatório para todos os clientes, tentei novamente e percebi que um Bairro também era obrigatório.

Acho que seria interessante colocar um aviso de que falta informação no endereço de entrega para o cliente poder atualizar as informações e refazer o pedido.  E também checar e avisar ao dono da loja que esses campos não são obrigatórios e pode resultar em erro na hora de concluir o pagamento.

**Comment by prestabr** [comment]
Bom Dia lucasdamo,

Obrigado por utilizar o módulo oficial e compartilhar conosco o seu feedback!

Esses problemas são realmente bem comuns. O módulo de checkout transparente está preparado para trabalhar com diversos padrões diferentes de cadastros, que são disponibilizados gratuitamente ou não na web, mas ele não tem o controle sobre o cadastro do endereço na loja.

O correto é configurar na loja a obrigatoriedade do campo referente ao numeral do endereço, cep, bairro, cidade, uf, etc, antes de pensar em lançar a loja para vender, até por conta da emissão de NF-e que é obrigatória e exige a captura dessas informações.

Interferir na navegabilidade do cliente dentro da loja com base em informações ausentes em seu cadastro não é algo viável. Mas nas próximas updates vamos considerar a possibilidade de validar se os campos estão marcados como obrigatórios nas configurações da loja, exibindo um alerta na tela de configuração do módulo.

No momento, em ambos os módulos (PS 1.6 e 1.7) contam validação e orientações sobre UF (se os estados estão ativos na configuração do país) e Sandbox.

Debug para soluçoes de problemas

PS 1.6: https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

PS 1.7: https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Registro de Transações & Gerenciamento de Logs

PS 1.6: https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#7---registro-de-transa%C3%A7%C3%B5es--gerenciamento-de-logs

Ps 1.7: https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#7---registro-de-transa%C3%A7%C3%B5es--gerenciamento-de-logs

Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
