### ISSUE TITLE
Modulo instalado nao aparece na guia Pagamentos

### ISSUE THREAD

**Issue by cunha-fabricio** [pagseguro/prestashop#90]
Olá, sempre usei este modulo mas na versão 1.7.6 ele nao aparece na guia de módulos de pagamento, me impossibilitando de utilizar outros modelos acessórios que preciso para minha loja. alguém sabe oq pode ser? obrigado
![Captura de Tela 2020-05-12 às 13 24 22](https://user-images.githubusercontent.com/58490559/81719821-ed245880-9453-11ea-8dd2-29ce0752da92.png)
![Captura de Tela 2020-05-12 às 13 24 00](https://user-images.githubusercontent.com/58490559/81719832-f1507600-9453-11ea-8370-7fef7ef5529c.png)

**Comment by prestabr** [comment]
Boa Tarde cunha-fabricio,

Obrigado por utilizar o módulo oficial da PragSeguro.

O módulo não é exibido em "Pagamentos > Métodos de Pagamento" porque ele não é nativo da PrestaShop e também não é oferecido na loja Addons. Essa tab só existe na PrestaShop 1.7 e é uma nova regra sugerida por eles para fins comerciais.

A única função dessa tab é exibir e agrupar os meios de pagamentos disponíveis. Você não terá problemas de usabilidade ou qualquer tipo de interferência negativa em sua loja por conta deste detalhe.

Não entendemos _"me impossibilitando de utilizar outros modelos acessórios que preciso para minha loja."_ consegue passar mais detalhes?

Atenciosamente,
Equipe PrestaBR

**Comment by cunha-fabricio** [comment]
O módulo da KnowBand para gerar aplicativos iOS e android lista como pagamento apenas os módulos presentes na guia 'pagamento'.

**Comment by prestabr** [comment]
Olá cunha-fabricio,

Não conhecemos este módulo, mas pesquisando, ele parece ser da loja Addons e por conta disto ele é compatível com a tab.

Infelizmente, este não é um problema de funcionamento do módulo da PagSeguro ou algum bug relacionado. Neste caso recomendamos que você tente entrar em contato com a KnowBand para sugerir melhorias e maior compatibilidade com outros módulos de pagamento.

Você pode sugerir para que todos os módulos que fizerem parte do contexto "payments_gateways" sejam listados como opção de pagamento, exemplo:

https://github.com/pagseguro/prestashop/blob/master/1.7.x/checkout-transparente/pagseguropro/pagseguropro.php

![Screenshot at 2020-05-12 16-18-47](https://user-images.githubusercontent.com/7054224/81736165-88c1c300-946c-11ea-938a-f32513efee17.png)

Atenciosamente,
Equipe PrestaBR
