### ISSUE TITLE
erro de token invalido e unknown web session id (hospedagem compartilhada trava sessionid)

### ISSUE THREAD

**Issue by marceonesgenesis** [pagseguro/prestashop#91]
sou novo aqui e queria configurar o meu prestashop junto com api do pagseguro, mas estou tendo estas dificuldades poderia me ajudar
![image](https://user-images.githubusercontent.com/24657626/81732366-c7547f00-9466-11ea-88e0-6e3817f495f5.png)
segue acima o problema encontrado

**Comment by prestabr** [comment]
Boa Tarde marceonesgenesis,

Obrigado por utilizar o módulo oficial da PagSeguro e seja muito bem-vindo! :)

Este travamento, "Token Web Inválido", pode ser originado por problemas de configuração de permissões de arquivos na hospedagem ou e-mail inválido na configuração do módulo.

a) Hospedagem

As permissões em /modules/pagseguropro/ devem ser 755 em diretórios e 644 em arquivos. O ideal é que você faça a correção para toda a /public_html/. Verifique com a sua hospedagem ou instale o pacote suhosin no php via easyapache 4 (se houver cpanel).

b) E-mail de Cadastro

PS 1.6.x: https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#1---ativa%C3%A7%C3%A3o

PS 1.7.x: https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#1---ativa%C3%A7%C3%A3o

Importante...:

Para evitar problemas com o processamento do pagamento sugerimos que torne
obrigatório os seguintes campos no cadastro do cliente: cpf, bairro, cidade, estado, telefone ou celular.

Lembrando que o cpf é sempre obrigatório para vendas via cartão de
crédito, independente se o cliente é PF ou PJ.

Atenciosamente,
Equipe PrestaBR

**Comment by marceonesgenesis** [comment]
boa tarde mesmo fazendo as devidas alterações conforme solicitada ainda assim permanece o problema, segue abaixo os prints do nosso ambiente.

![image](https://user-images.githubusercontent.com/24657626/81737999-549bd180-946f-11ea-83d8-3acc6ffc4505.png)
![image](https://user-images.githubusercontent.com/24657626/81738012-5b2a4900-946f-11ea-8cde-b34283401011.png)
![image](https://user-images.githubusercontent.com/24657626/81738053-6b422880-946f-11ea-828a-8b2bb4203ff9.png)

**Comment by prestabr** [comment]
Olá marceonesgenesis,

Você aplicou as permissões de forma recursiva?

Você tem certeza que o seu e-mail de cadastro está correto e não tem nenhuma pendência (documentação, validação de conta de email, etc) na PagSeguro?

Confere novamente por favor...

Atenciosamente,
Equipe PrestaBR

**Comment by marceonesgenesis** [comment]
então esta tudo verificado mas não sei o que ocorre, e a conta está validade e sendo utilizada
já envio link de pagamento mas dentro da plataforma do proprio pagseguro.

**Comment by prestabr** [comment]
Olá marceonesgenesis,

Tem algum detalhe que deve ter passado batido... 

Faz o seguinte, libera um acesso ao seu FTP e ao backoffice da sua loja e encaminha para nós, vamos verificar para você. E-mail: sac@prestabr.com.br

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Olá marceonesgenesis,

Obrigado por ter encaminhado os dados de acesso para o nosso e-mail.

Analisamos a questão do e-mail + token e permissões no FTP, estes detalhes estão Ok.

Fizemos diversos testes e aparentemente está tudo 100% com o módulo e com a sua loja, o que parece estar causando problemas é a Hospedagem. Talvez esteja faltando algum detalhe de configuração no Host (apache ou php) por ele ser do tipo compartilhado ou existe algum problema de conectividade.

Basicamente o módulo precisa conseguir gerar o SessionID para iniciar o processo de pagamento na tela de checkout, você pode testar dessa forma:

Em sua hospedagem: https://sempreprontamodas.com.br/modules/pagseguropro/update.php?acao=session

![Screenshot at 2020-05-12 20-24-50](https://user-images.githubusercontent.com/7054224/81755479-465dad80-948f-11ea-8910-ced5a2629dc3.png)

Em outra hospedagem, como deve retornar:

![Screenshot at 2020-05-12 20-24-40](https://user-images.githubusercontent.com/7054224/81755537-6ee5a780-948f-11ea-9982-e79af2c54316.png)

Para a plataforma PrestaShop o ideal seria utilizar uma hospedagem do tipo VPS. Hospedagens do tipo Compartilhada geralmente são recomendadas para softwares menos complexos como sites e landingpages que não exigem diversos recursos e processamento de dados.

Atenciosamente,
Equipe PrestaBR

**Comment by marceonesgenesis** [comment]
então se eu pegar meu site + banco de dados do jeito que está la e colocar em um servidor melhor tipo digitalocean com serviço dedicado é pra ela funcionar perfeitamente ne

**Comment by prestabr** [comment]
Bom Dia marceonesgenesis,

> então se eu pegar meu site + banco de dados do jeito que está la e colocar em um servidor melhor tipo digitalocean com serviço dedicado é pra ela funcionar perfeitamente ne

Exatamente, assim que migrar você pode testar novamente https://sempreprontamodas.com.br/modules/pagseguropro/update.php?acao=session.

Atenciosamente,
Equipe PrestaBR
