### ISSUE TITLE
"Data de Nascimento Não Preenchido"  desabilita botão CONFIRMAR

### ISSUE THREAD

**Issue by glaucomodera** [pagseguro/prestashop#92]
Olá meus queridos, 
Boa tarde. 
Venho reportar um problema. 
Quando o cliente tenta efetuar o pagamento sem a data de nascimento o sistema acusa o erro:  "Data de Nascimento Não Preenchida". Nesse momento, o botão CONFIRMAR fica desabilitado e a quantidade de parcelas apaga. Até aí ok.
 
Mesmo quando o cliente digita a data de nascimento e preenche novamente a quantidade de parcelas, o botão CONFIRMAR continua desabilitado. 

A única forma de re-habilitar o botão CONFIRMAR é apagar todos os dados do cartão manualmente (número, validade e CVV) e re-digitar todos os dados do referido cartão. 

Acredito que seja um erro, pois o botão CONFIRMAR deveria ficar novamente disponível assim que o cliente digitasse a data de nascimento e a quantidade de parcelas. Ou deveria apagar tudo quando desse o erro de data de nascimento. 
Segue uma foto 
![data de nascimento](https://user-images.githubusercontent.com/56834125/81846335-4c539d00-9528-11ea-8ff9-a3b11bf644c2.JPG)

**Comment by prestabr** [comment]
Boa Tarde glaucomodera,

Agradecemos o seu feedback!

> Olá meus queridos,
> Boa tarde.
> Venho reportar um problema.
> Quando o cliente tenta efetuar o pagamento sem a data de nascimento o sistema acusa o erro: "Data de Nascimento Não Preenchida". Nesse momento, o botão CONFIRMAR fica desabilitado e a quantidade de parcelas apaga. Até aí ok.
> 
> Mesmo quando o cliente digita a data de nascimento e preenche novamente a quantidade de parcelas, o botão CONFIRMAR continua desabilitado.
> 

Confere este issue: https://github.com/pagseguro/prestashop/issues/83#issuecomment-620126207

> A única forma de re-habilitar o botão CONFIRMAR é apagar todos os dados do cartão manualmente (número, validade e CVV) e re-digitar todos os dados do referido cartão.
> 
> Acredito que seja um erro, pois o botão CONFIRMAR deveria ficar novamente disponível assim que o cliente digitasse a data de nascimento e a quantidade de parcelas. Ou deveria apagar tudo quando desse o erro de data de nascimento.
> Segue uma foto
> ![data de nascimento](https://user-images.githubusercontent.com/56834125/81846335-4c539d00-9528-11ea-8ff9-a3b11bf644c2.JPG)

Vamos analisar os detalhes e se for viável vamos aplicar eventuais melhorias nas próximas versões do módulo.

Para evitar problemas com o processamento do pagamento sugerimos que torne
obrigatório os seguintes campos no cadastro do cliente: cpf, endereço, numeral do endereço, bairro, cidade, uf, telefone ou celular e aniversário.

Atenciosamente,
Equipe PrestaBR

**Comment by glaucomodera** [comment]
Olá, obrigado pelo retorno. Acontece que o cadastro feito pelas redes sociais (social login) não fornecem a data de nascimento. Daí o cliente acaba por não preecher esse campo.

**Comment by glaucomodera** [comment]
Por favor, pelo menos apaguem o campo CVV também quando dá erro de data de nascimento. Assim quando o cliente Digitar o CVV e Parcelas o botão CONFIRMAR volta.

**Comment by zagalux** [comment]
Estou com o mesmo problema, conseguiu resolver @glaucomodera ? 
Já resolvi a parte do termos e condições, porém o problema aqui é que o módulo faz com que o cliente tenha que clicar novamente em algum dado do cartão para reabilitar as parcelas e ele escolher de novo, assim o cliente acaba ficando perdido em o que fazer. Já tive muito problema com isso.

**Comment by glaucomodera** [comment]
Olá amigo, não consegui resolver. Quando o cliente entra no meu site via rede social, não é captado a data de nascimento. Em fim, estou aguardando um update da comunidade PrestaBR aqui pra atualizar o módulo.
