### ISSUE TITLE
Desconto 1x no cartão (Customização/Sugestão)

### ISSUE THREAD

**Issue by jfcbxp** [pagseguro/prestashop#93]
Primeiramente muito obrigado por esse modulo incrível amigo, tenho uma necessidade de adicionar desconto também quando o cliente comprar em 1x no cartão, poderia me dar uma dica de como fazer essa implementação

**Comment by prestabr** [comment]
Bom Dia jfcbxp,

Agradecemos o seu feedback!

Desconto no pagamento via cartão é uma demanda bem incomum, mas você pode aplicar o desconto acessando o arquivo /pagseguropro/controllers/front/validation.php, localiza essa linha:

`if ($this->tipo_pagamento == 'cartao') {`

E add esse trecho de código logo em seguida, exemplo:

```
if(Tools::getValue('ps_cartao_parcelas') == 1)
{
	$this->module->geraDesconto($this->context->cart);
}
```

![Screenshot at 2020-05-20 09-41-25](https://user-images.githubusercontent.com/7054224/82447340-89ff7b00-9a7e-11ea-82af-30bf75bab260.png)

Na sequência você precisará definir o nome do voucher, descrição, tipo e valor de desconto, acessa o arquivo /pagseguropro/pagseguropro.php, localiza a função `public function geraDesconto($cart)` e é só seguir o modelo e customizar de acordo com a sua necessidade, levando em consideração que o boleto utiliza o mesmo mecanismo.

Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR

**Comment by jfcbxp** [comment]
Muito obrigado pela resposta, mas tive um problema com a solução.
quando digito os dados do cartão e clico em confirmar(esse é o momento que ele vai executar a função geraDesconto)

o modulo retorna a mensagem "forma de pagamento temporariamente indisponivel. Por favor tente novamente ou escolha outra forma de pagamento"

mas se eu simplesmente fechar essa mensagem e tentar novamente funciona.

acredito que o geraDesconto por algum motivo não esta deixando o modulo finalizara transação. 
mas na segunda tentativa que o cupom já esta aplicado, a a transação é realizada.

**Comment by prestabr** [comment]
Ola jfcbxp,

Você pode tentar identificar a origem do problema na área de Logs do módulo:

PS 1.6: https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#7---registro-de-transa%C3%A7%C3%B5es--gerenciamento-de-logs

PS 1.7: https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#7---registro-de-transa%C3%A7%C3%B5es--gerenciamento-de-logs

Ao acessar, confere como verificar os logs e localizar a resposta da API: #75 (comment) (Leia com calma...)

A função geraDesconto é válida para o Boleto, por isso comentamos...: _levando em consideração que o boleto utiliza o mesmo mecanismo_.

Se você não tiver experiência com programação ou não tiver o auxílio de um profissional experiente, não recomendamos que realize as customizações no módulo, você pode acabar gerando outros problemas imprevisíveis.

Desejamos Boa Sorte com o seu projeto! :)

Atenciosamente,
Equipe PrestaBR
