### ISSUE TITLE
Olá

### ISSUE THREAD

**Issue by cunha-fabricio** [pagseguro/prestashop#94]
Estou tentando usar PagSeguro na minha loja prestashop, no Pc funciona bem, mas no celular na hora do pagamento os campos numero, bairro e data de nascimento aparecem como se nao tivessem sido preenchidos (borda vermelha) me impedindo de fechar a compra, poderia me dizer se fiz algo errado? obrigado.

**Comment by prestabr** [comment]
Bom Dia cunha-fabricio,

O módulo não diferencia o dispositivo para realizar a validação dos campos obrigatórios na tela de pagamento. Se funciona pra um tem que funcionar para o outro também, a menos que exista algum conflito de JavaScript ou customização de mobile em sua loja/layout.

Tenta utilizar o inspetor de elementos do seu navegador para simular o mobile, assim você pode visualizar a tab do console e tentar localizar o problema.

Debug para soluçoes de problemas:

PS 1.6: https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

PS 1.7: https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Atenciosamente,
Equipe PrestaBR
