### ISSUE TITLE
Problema com erro de JS no tema padrão (PrestaShop 1.6)

### ISSUE THREAD

**Issue by r7jacob** [pagseguro/prestashop#97]
Olá, bom dia.

Montamos uma loja 1.6 do zero para testarmos a integração e está apresentando o erro abaixo no console do navegador: 
![image](https://user-images.githubusercontent.com/3713595/82820884-6622a780-9e79-11ea-814e-ca410fe871fc.png)

O servidor que esta loja está hospedada está de acordo com todos os requisitos do PS 1.6.
Nenhum CCC ativo e nenhuma forma de cache ativa também. Modo debug desativado.

Mapeamento de campos trazendo as informações corretas:
![image](https://user-images.githubusercontent.com/3713595/82821155-f103a200-9e79-11ea-83c7-834c688151e3.png)

Detalhe da linha que contem o erro:
![image](https://user-images.githubusercontent.com/3713595/82820999-a7b35280-9e79-11ea-8e34-1ece56277fe1.png)

Caso queira validar algo em nosso ambiente de teste, podemos passar o link da loja.

**Comment by prestabr** [comment]
Bom Dia r7jacob,

O seu print indica que o módulo está com dificuldades para criar o SessionID. Basicamente o módulo precisa conseguir gerar o SessionID para iniciar o processo de pagamento na tela de checkout.

Este problema geralmente é originado pelo servidor de hospedagem, o erro na tela do módulo é o "unknown web session id".

Você pode verificar se a hospedagem está ok tentando gerar o SessionID desta forma:

https://www.minhaloja.com.br/modules/pagseguropro/update.php?acao=session

Exemplo de retorno:

![82818259-d4b13680-9e74-11ea-8ad6-9b5dd1aec9e6](https://user-images.githubusercontent.com/7054224/82821885-3ffe0700-9e7b-11ea-9a67-4d808844a7d1.png)

Atenciosamente,
Equipe PrestaBR

**Comment by r7jacob** [comment]
Sim, claro. Exibe isso aqui ao acessar o link indicado (https://ps16.paradadigital.com.br/modules/pagseguropro/update.php?acao=session):

![image](https://user-images.githubusercontent.com/3713595/82822696-9455b680-9e7c-11ea-8a6e-cc22de2eb688.png)

**Comment by prestabr** [comment]
Olá r7jacob,

Mesma questão neste issue: https://github.com/pagseguro/prestashop/issues/88#issuecomment-626994811

Se você já seguiu as orientações do comentário acima e não resolveu então é preciso conferir a hospedagem. O ideal é que você use o PHP 7.0 ou 7.0.33 com a PrestaShop 1.6.1.24. Com o PHP 7.1 até 7.4 vários outros problemas surgirão. Usando a PrestaShop 1.7, o ideal é utilizar o PHP 7.1 até 7.3 (com algumas ressalvas de warnings).

Para a plataforma PrestaShop o ideal seria utilizar uma hospedagem do tipo VPS. Hospedagens do tipo Compartilhada geralmente são recomendadas para softwares menos complexos como sites e landingpages que não exigem diversos recursos e processamento de dados.

Se estiver usando cPanel e já rodou o easyapache4 para recompilar o php confere se os pacotes básicos de configuração estão ativos para a versão selecionada.

> Sim, claro. Exibe isso aqui ao acessar o link indicado:(https://ps16.paradadigital.com.br/modules/pagseguropro/update.php?acao=session):
> 
> ![image](https://user-images.githubusercontent.com/3713595/82822696-9455b680-9e7c-11ea-8a6e-cc22de2eb688.png)
> 
> Caso queira fazer algum teste, pode fazer, pois é uma loja de desenvolvimento nossa :)

Exemplo: https://prestabr.com.br/ps16/modules/pagseguropro/update.php?acao=session

Exemplo aleatório de outra loja atendida aqui no Git: https://modera.com.br/modules/pagseguropro/update.php?acao=session

Atenciosamente,
Equipe PrestaBR

**Comment by r7jacob** [comment]
É possível que vocês estão deixando de informar algum requisito fundamental para a integração?

Pois todos os requisitos do PS 1.6 e todos os requisitos do seu módulo estão sendo atendidos.
Tem algum recurso específico que está faltando ativarmos?

Veja nosso painel:
![image](https://user-images.githubusercontent.com/3713595/82825501-be5da780-9e81-11ea-98fe-948537e16682.png)

Já testamos em 3 servidores diferentes (na locaweb, na hostgator e em uma VPS otimizada para PS) e em nenhum deles está funcional.

**Comment by prestabr** [comment]
Olá r7jacob,

> É possível que vocês estão deixando de informar algum requisito fundamental para a integração?

Os requisitos do módulo são bem básicos, o mais simples possível, nada além do default no Apache/PHP:

```
- Este módulo não utiliza Override;
- Compatível com o todas as versões da série 1.6.x da PrestaShop;
- Testado e desenvolvido com base na API v.2 e v.3 do PagSeguro;
- Compatível com PHP 5.4.x à 7.x.x;
- Requer a biblioteca cURL ativa na hospedagem.
- Obrigatório o uso de certificado SSL com o protocolo TLS 1.2;
```

> 
> Pois todos os requisitos do PS 1.6 e todos os requisitos do seu módulo estão sendo atendidos.
> Tem algum recurso específico que está faltando ativarmos?
> 
> Veja nosso painel:
> 
> ![image](https://user-images.githubusercontent.com/3713595/82825501-be5da780-9e81-11ea-98fe-948537e16682.png)
> 
> Já testamos em 3 servidores diferentes (na locaweb, na hostgator e em uma VPS otimizada para PS) e em nenhum deles está funcional.

Aparentemente está tudo ok. É a primeira vez que vemos específicamente essas saídas de erro:

![82822696-9455b680-9e7c-11ea-8a6e-cc22de2eb688](https://user-images.githubusercontent.com/7054224/82825982-a175a400-9e82-11ea-91f3-f20114dfb212.png)

Essa linha Unauthorized 2073 indica que o cURL não conseguiu obter uma resposta na conexão.

Você já verificou se o token configurado no módulo está correto? O token de produção é diferente do sandbox.

Verifica também se a hospedagem tem algum firewall. Faz esse teste de conectividade via SSH: 
` curl -X POST https://ws.pagseguro.uol.com.br/v2/sessions -d "email=SEU_EMAIL_NO_PAGSEGURO&token=SEU_TOKEN_DE_PRODUCAO"`

Atenciosamente,
Equipe PrestaBR

**Comment by r7jacob** [comment]
Quanto aos requisitos, todos eles estão ok.

Segue o teste solicitado:
`[root@sandbox ~]# curl -X POST https://ws.pagseguro.uol.com.br/v2/sessions -d "email=pagamento@neogest.com.br&token=F5C4A2A55C5C415CC4D12F884561913C"
Unauthorized`

Chave de acesso:
![image](https://user-images.githubusercontent.com/3713595/82827892-5067af00-9e86-11ea-868b-f6f5e8857b1f.png)

Autorização concedida:
![image](https://user-images.githubusercontent.com/3713595/82827936-68d7c980-9e86-11ea-847c-228961eb6d31.png)


Comente esta parte não que vou editar posteriormente para ocultar nossas informações. :)

**Comment by prestabr** [comment]
Olá r7jacob,

> Quanto aos requisitos, todos eles estão ok.
> 
> Segue o teste solicitado:
> `[root@sandbox ~]# curl -X POST https://ws.pagseguro.uol.com.br/v2/sessions -d "email=[pagamento@neogest.com.br](mailto:pagamento@neogest.com.br)&token=F5C4A2A55C5C415CC4D12F884561913C"
> 
> Unauthorized`

Unauthorized = Não autorizado  

Você deveria ter recebido essa resposta, exemplo:

`?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><session><id>cebda96113954b9aa65ba190ed784145</id></session>`

Qualquer coisa diferente disso pode indicar algum outro problema com sua conta ou serviço de hospedagem.

São 2 únicas hipóteses e é com você:

**a)** Existe algum problema de conectividade na hospedagem. Se você não tem o controle sobre a hospedagem para depurar este problema, ou não sabe se tem um firewall ou qualquer tipo de bloqueio, abra um ticket na hospedagem e solicite a liberação. Passa pra eles o teste de conectividade via SSH.

**b)** O email de cadastro e token estão incorretos. Vale lembrar que a conta precisa ser do tipo Vendedor ou Empresarial, não pode ser Conta Pessoal.
> 
> Chave de acesso:
> ![image](https://user-images.githubusercontent.com/3713595/82827892-5067af00-9e86-11ea-868b-f6f5e8857b1f.png)
> 
> Autorização concedida:
> ![image](https://user-images.githubusercontent.com/3713595/82827936-68d7c980-9e86-11ea-847c-228961eb6d31.png)
> 
> Comente esta parte não que vou editar posteriormente para ocultar nossas informações. :)

Atenciosamente,
Equipe PrestaBR

**Comment by r7jacob** [comment]
Com os servidores não tem nada que possa estar causando o bloqueio não, fizemos todos os testes do nosso lado aqui.

Tenho total acesso ao nosso servidor e posso extrair toda a informação que precisar, porém tudo indica mesmo um erro de codificação do módulo.

Tem mais alguma coisa que queira que façamos o teste?

Com a conta também acredito que não tenha nada irregular, pois é uma conta Empresarial:
![image](https://user-images.githubusercontent.com/3713595/82835096-67fc6300-9e99-11ea-9099-8ed5830515aa.png)

**Comment by r7jacob** [comment]
Credito que o problema esteja na criação do APP no PagSeguro que o módulo está fazendo.

Ao clicar no ASSINE JÁ, solicita o login da conta no pagseguro, após autenticarmos, exibe esta mensagem:
![image](https://user-images.githubusercontent.com/3713595/82835873-a98e0d80-9e9b-11ea-8a23-a30d0ffd0563.png)

Porém, ao acessar a conta, o APP não existe:
![image](https://user-images.githubusercontent.com/3713595/82835921-bf9bce00-9e9b-11ea-9f34-c861b19b6fe7.png)

E se criamos manualmente não funciona, como reportado anteriormente.

**Comment by r7jacob** [comment]
Realmente o problema é com a codificação do mesmo.
Com poucos debugs que colocamos dá para identificar que o $data que está recebendo na função está vazio:

![image](https://user-images.githubusercontent.com/3713595/82837095-7f8a1a80-9e9e-11ea-81e1-286913b8f6a9.png)


![image](https://user-images.githubusercontent.com/3713595/82837133-929cea80-9e9e-11ea-90bd-0f7b5df271e4.png)

**Comment by prestabr** [comment]
Olá r7jacob,

Só pra gente tentar organizar as coisas... 

Quando você informa o token + email e tenta acessar o checkout o SessionID é capturado corretamente? Já conferiu utilizando o Debug? Consegue confirmar?https://github.com/pagseguro/prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro

Outra coisa, agora quando você tenta utilizar o APP, não funciona? Sendo uma conta de vendedor ou empresarial é preciso aguardar a validação por parte do PagSeguro. Enquanto não for liberado não há o que fazer, tem que usar a configuração email + token.

Atenciosamente,
Equipe PrestaBR

**Comment by r7jacob** [comment]
Parece ter funcionado.

Por favor, poderia excluir ou ocultar esta issue?
Pois tem dados da nossa conta expostos.

Obrigado.

**Comment by prestabr** [comment]
Olá r7jacob,

> Parece ter funcionado.

Ótimo, obrigado por confirmar.

> Por favor, poderia excluir ou ocultar esta issue?
> Pois tem dados da nossa conta expostos.

Tá ok, vamos editar/remover qualquer dado confidencial.

> Obrigado.
