### ISSUE TITLE
Dado incorreto desabilita finalizar transação até reinserir os dados do cartão.

### ISSUE THREAD

**Issue by zagalux** [pagseguro/prestashop#98]
No issue #92 o colega relatou um problema que também estou tendo.

 Quando o cliente insere alguma informação errada recebe uma mensagem de erro e o botão para confirmar fica desabilitado para que ele arrume o erro e tente novamente. 
 Porém o botão só reabilita quando o cliente escolhe novamente o número de parcelas, que quando tem algum erro no preenchimento é setado para - novamente e pede para que seja escolhido novamente.

Mas o botão de escolher parcelas fica desabilitado até que o cliente altere ou clique novamente no número do cartão. 

Gerando muita confusão nos clientes e que alguns não consigam finalizar o pedido por cartão.

 Já resolvi a questão do "termos e condições", já está desabilitado, esse é um problema no preenchimento dos dados do cartão.

**Comment by prestabr** [comment]
Bom Dia zagalux,

Confere esta explicação a respeito do funcionamento do checkout: https://github.com/pagseguro/prestashop/issues/63#issuecomment-543036063

Este é o processo normal de compra seguindo os padrões e regras de segurança da API de pagamentos. Como mencionado neste comment https://github.com/pagseguro/prestashop/issues/92#issue-617636714 o botão de "comprar" fica desabilitado, é um problema na mesma linha do "termos e condições" que resolvemos para você.

Estamos analisando todos os detalhes e trabalhando para resolver qualquer bug causado pelo módulo ou pela própria PrestaShop. A próxima update está previsa para +- 20 dias.

Atenciosamente,
Equipe PrestaBR

**Comment by zagalux** [comment]
Teria como então apagar o número do cartão já inserido? Para que o cliente saiba que precisa reinserir e confirmar esses dados?

**Comment by zagalux** [comment]
@prestabr Alguma modificação no código que eu poderia fazer por enquanto para apagar o numero do cartao e alertar o cliente?

**Comment by prestabr** [comment]
Olá zagalux,

Não recomendamos nenhuma modificação nessa área de checkout. Estamos analisando todos os detalhes e trabalhando para resolver qualquer bug causado pelo módulo ou pela própria PrestaShop. A próxima update está previsa para +- 20 dias.

Atenciosamente,
Equipe PrestaBR
