### ISSUE TITLE
falha na finalização do pagamento (cliente com cadastro incompleto [UF])

### ISSUE THREAD

**Issue by rafachiarello** [pagseguro/prestashop#99]
olá!
meu set: Prestashop v.1.7.6.2; módulo Pagseguro v.1.0.3; 

estou enfrentando o seguinte problema na minha loja: ao selecionar a opção de pagamento por transferência bancária (débito online), em qualquer das opções de banco, retorna a mensagem de erro em pop-up "Forma de pagamento temporariamente indisponível..."
![pagseguro - erro transferencia bancaria](https://user-images.githubusercontent.com/60196289/83451455-5ed93c00-a42d-11ea-8921-d47723b7d622.jpg)

constatações:
- cartão de crédito e boleto estão funcionando;
- no painel da minha conta do Pagseguro (Empresarial + verificada) todas as formas de recebimento estão habilitadas (inclusive débito online)

obrigado, aguardo
Rafael

**Comment by prestabr** [comment]
Boa Tarde rafachiarello,

Obrigado por utilizar o módulo oficial da PagSeguro em sua loja! :)

Para identificar a origem do problema é preciso acessar a área de Logs do módulo:
https://github.com/pagseguro/prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#7---registro-de-transa%C3%A7%C3%B5es--gerenciamento-de-logs

Ao acessar, confere como verificar os logs e localizar a resposta da API: https://github.com/pagseguro/prestashop/issues/75#issuecomment-567057058 (Leia com calma...)

Qualquer dúvida é só retornar.

Atenciosamente,
Equipe PrestaBR

**Comment by rafachiarello** [comment]
Olá!
Obrigado pelo breve retorno.
Após analisar os logs, conforme recomendação, verifiquei que o erro ocorria devido a falta de um dado do cadastro do cliente (Estado).
Agradeço a atenção!
Bom trabalho!

**Comment by prestabr** [comment]
Boa Tarde rafachiarello,

Ótimo, agradecemos o seu feedback. Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
